// frontend-react/src/components/charts/BarChart.tsx
interface BarChartProps {
  data?: any[]
  labelKey: string
  valueKey: string
  color?: string
  width?: number
}

const PADDING = 100
const BAR_HEIGHT = 30

export default function BarChart({
  data = [],
  labelKey,
  valueKey,
  color = '#0d6efd',
  width = 400,
}: BarChartProps) {
  if (!data.length) {
    return <div className="text-center text-muted py-3">Немає даних</div>
  }

  const height = data.length * BAR_HEIGHT + PADDING
  const maxValue = Math.max(...data.map(item => item[valueKey] || 0), 1)
  const maxBarWidth = width - PADDING - 80

  const items = data.map(item => ({
    label: item[labelKey] || 'Unknown',
    value: item[valueKey] || 0,
    barWidth: ((item[valueKey] || 0) / maxValue) * maxBarWidth,
  }))

  return (
    <div style={{ width: '100%' }}>
      <svg width={width} height={height}>
        {items.map((item, idx) => (
          <g key={idx}>
            <rect
              x={PADDING}
              y={PADDING + idx * BAR_HEIGHT}
              width={item.barWidth}
              height={BAR_HEIGHT - 5}
              fill={color}
            />
            <text
              x={PADDING - 5}
              y={PADDING + idx * BAR_HEIGHT + BAR_HEIGHT / 2 + 4}
              textAnchor="end"
              fontSize="12"
              fill="#666"
            >
              {item.label}
            </text>
            <text
              x={PADDING + item.barWidth + 5}
              y={PADDING + idx * BAR_HEIGHT + BAR_HEIGHT / 2 + 4}
              fontSize="12"
              fill="#333"
              fontWeight="bold"
            >
              {item.value}
            </text>
          </g>
        ))}
      </svg>
    </div>
  )
}

// frontend/src/components/BarChart.vue
<template>
  <div class="bar-chart">
    <svg :width="width" :height="height" v-if="items.length">
      <g v-for="(item, idx) in items" :key="idx">
        <rect
          :x="padding"
          :y="padding + idx * barHeight"
          :width="item.barWidth"
          :height="barHeight - 5"
          :fill="color"
        />
        <text
          :x="padding - 5"
          :y="padding + idx * barHeight + barHeight / 2 + 4"
          text-anchor="end"
          font-size="12"
          fill="#666"
        >
          {{ item.label }}
        </text>
        <text
          :x="padding + item.barWidth + 5"
          :y="padding + idx * barHeight + barHeight / 2 + 4"
          font-size="12"
          fill="#333"
          font-weight="bold"
        >
          {{ item.value }}
        </text>
      </g>
    </svg>
    <div v-else class="text-center text-muted py-3">Немає даних</div>
  </div>
</template>

<script setup>
import { computed } from 'vue'

const props = defineProps({
  data: { type: Array, default: () => [] },
  labelKey: { type: String, required: true },
  valueKey: { type: String, required: true },
  title: { type: String, default: '' },
  color: { type: String, default: '#0d6efd' },
  width: { type: Number, default: 400 },
})

const padding = 100
const barHeight = 30

const height = computed(() => {
  return (props.data?.length || 1) * barHeight + padding
})

const maxValue = computed(() => {
  return Math.max(...(props.data?.map(item => item[props.valueKey]) || [1]))
})

const items = computed(() => {
  if (!props.data || !props.data.length) return []

  const maxBarWidth = props.width - padding - 80

  return props.data.map(item => ({
    label: item[props.labelKey] || 'Unknown',
    value: item[props.valueKey] || 0,
    barWidth: ((item[props.valueKey] || 0) / maxValue.value) * maxBarWidth,
  }))
})
</script>

<style scoped>
.bar-chart {
  width: 100%;
}
</style>
