// frontend-react/src/components/FilterSidebar.tsx
import { useState, useEffect } from 'react'

interface FilterValue {
  value: string
  label?: string
  count: number
}

interface FilterGroup {
  field: string
  label: string
  values: FilterValue[]
}

interface FilterSidebarProps {
  namespace: string
  groups: FilterGroup[]
  activeFilters: Record<string, string>
  onToggle: (params: { field: string; value: string }) => void
}

export default function FilterSidebar({ namespace, groups, activeFilters, onToggle }: FilterSidebarProps) {
  const [collapsed, setCollapsed] = useState(false)
  const storageKey = `admin.filterSidebar:${namespace}`

  useEffect(() => {
    try {
      const stored = JSON.parse(localStorage.getItem(storageKey) || '{}')
      if (typeof stored.collapsed === 'boolean') {
        setCollapsed(stored.collapsed)
      }
    } catch {
      // Invalid JSON - ignore
    }
  }, [storageKey])

  function isActive(field: string, value: string) {
    return activeFilters[field] === value
  }

  function toggleCollapsed() {
    const newCollapsed = !collapsed
    setCollapsed(newCollapsed)
    localStorage.setItem(storageKey, JSON.stringify({ collapsed: newCollapsed }))
  }

  return (
    <aside className={`filter-sidebar ${collapsed ? 'collapsed' : ''}`}>
      <div className="d-flex justify-content-between align-items-center mb-3">
        {!collapsed && <h6 className="mb-0">Фільтри</h6>}
        <button
          className="btn btn-sm btn-link p-0"
          onClick={toggleCollapsed}
          title={collapsed ? 'Розгорнути' : 'Згорнути'}
        >
          <i className={`bi ${collapsed ? 'bi-chevron-double-right' : 'bi-chevron-double-left'}`} />
        </button>
      </div>

      {!collapsed && (
        <>
          {groups.map(group => (
            <div key={group.field} className="mb-3">
              <div className="text-muted small fw-semibold mb-2">{group.label}</div>
              {group.values.map(item => (
                <button
                  key={item.value}
                  className={`btn btn-sm w-100 text-start d-flex justify-content-between align-items-center mb-1 ${
                    isActive(group.field, item.value) ? 'btn-primary' : 'btn-outline-secondary'
                  }`}
                  onClick={() => onToggle({ field: group.field, value: item.value })}
                >
                  <span className="text-truncate">{item.label ?? item.value}</span>
                  <span
                    className={`badge ms-2 ${
                      isActive(group.field, item.value) ? 'bg-light text-dark' : 'bg-secondary'
                    }`}
                  >
                    {item.count}
                  </span>
                </button>
              ))}
            </div>
          ))}
        </>
      )}

      <style>{`
        .filter-sidebar {
          min-width: 220px;
          max-width: 280px;
          padding: 1rem;
          background: var(--bs-secondary-bg);
          border-right: 1px solid var(--bs-border-color);
          transition: min-width 0.2s, max-width 0.2s;
        }

        .filter-sidebar.collapsed {
          min-width: 50px;
          max-width: 50px;
        }

        .filter-sidebar .btn {
          font-size: 0.875rem;
        }

        .filter-sidebar .text-truncate {
          overflow: hidden;
          text-overflow: ellipsis;
          white-space: nowrap;
        }
      `}</style>
    </aside>
  )
}

// frontend/src/components/FilterSidebar.vue
<!-- Copyright (c) 2026 Oleksandr Nosov. MIT License. -->
<template>
  <aside class="filter-sidebar" :class="{ collapsed }">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h6 v-if="!collapsed" class="mb-0">Фільтри</h6>
      <button
        class="btn btn-sm btn-link p-0"
        @click="toggleCollapsed"
        :title="collapsed ? 'Розгорнути' : 'Згорнути'"
      >
        <i :class="['bi', collapsed ? 'bi-chevron-double-right' : 'bi-chevron-double-left']"></i>
      </button>
    </div>

    <template v-if="!collapsed">
      <div v-for="group in groups" :key="group.field" class="mb-3">
        <div class="text-muted small fw-semibold mb-2">{{ group.label }}</div>
        <button
          v-for="item in group.values"
          :key="item.value"
          class="btn btn-sm w-100 text-start d-flex justify-content-between align-items-center mb-1"
          :class="isActive(group.field, item.value) ? 'btn-primary' : 'btn-outline-secondary'"
          @click="$emit('toggle', { field: group.field, value: item.value })"
        >
          <span class="text-truncate">{{ item.label ?? item.value }}</span>
          <span
            class="badge ms-2"
            :class="isActive(group.field, item.value) ? 'bg-light text-dark' : 'bg-secondary'"
          >
            {{ item.count }}
          </span>
        </button>
      </div>
    </template>
  </aside>
</template>

<script setup>
import { ref, computed, watch, onMounted } from 'vue'

const props = defineProps({
  /** Namespace для localStorage (щоб різні сторінки не ділили стан) */
  namespace: { type: String, required: true },
  /** Групи фільтрів: [{ field, label, values: [{ value, count, label? }] }] */
  groups: { type: Array, required: true },
  /** Поточні значення фільтрів { field: value } */
  activeFilters: { type: Object, default: () => ({}) },
})

defineEmits(['toggle'])

const STORAGE_KEY = computed(() => `admin.filterSidebar:${props.namespace}`)

const collapsed = ref(false)

function isActive(field, value) {
  return props.activeFilters[field] === value
}

function toggleCollapsed() {
  collapsed.value = !collapsed.value
  localStorage.setItem(STORAGE_KEY.value, JSON.stringify({ collapsed: collapsed.value }))
}

onMounted(() => {
  try {
    const stored = JSON.parse(localStorage.getItem(STORAGE_KEY.value) || '{}')
    if (typeof stored.collapsed === 'boolean') {
      collapsed.value = stored.collapsed
    }
  } catch {
    // Битий JSON — ігноруємо
  }
})
</script>

<style scoped>
.filter-sidebar {
  min-width: 220px;
  max-width: 280px;
  padding: 1rem;
  background: var(--bs-secondary-bg);
  border-right: 1px solid var(--bs-border-color);
  transition: min-width 0.2s, max-width 0.2s;
}

.filter-sidebar.collapsed {
  min-width: 50px;
  max-width: 50px;
}

.filter-sidebar .btn {
  font-size: 0.875rem;
}

.filter-sidebar .text-truncate {
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}
</style>
