// frontend-react/src/list-framework/components/RecordNavigator.tsx
interface RecordNavigatorProps {
  position: number | null
  totalCount: number
  hasPrev: boolean
  hasNext: boolean
  busy: boolean
  onPrev: () => void
  onNext: () => void
}

export default function RecordNavigator({
  position,
  totalCount,
  hasPrev,
  hasNext,
  busy,
  onPrev,
  onNext,
}: RecordNavigatorProps) {
  return (
    <div className="d-inline-flex align-items-center" style={{ gap: '0.125rem', marginRight: '2rem' }}>
      <button
        className="btn btn-sm btn-outline-secondary py-0 px-2"
        disabled={!hasPrev || busy}
        title="Попередній запис"
        onClick={onPrev}
      >
        ‹
      </button>
      <span
        className="text-muted small font-monospace"
        style={{ minWidth: '4rem', textAlign: 'center' }}
      >
        {busy ? (
          <span
            className="spinner-border spinner-border-sm"
            style={{ width: '0.7rem', height: '0.7rem' }}
          />
        ) : (
          `${position ?? '—'} / ${totalCount}`
        )}
      </span>
      <button
        className="btn btn-sm btn-outline-secondary py-0 px-2"
        disabled={!hasNext || busy}
        title="Наступний запис"
        onClick={onNext}
      >
        ›
      </button>
    </div>
  )
}

// frontend/src/components/RecordNavigator.vue
<template>
  <div class="d-inline-flex align-items-center" style="gap: 0.125rem; margin-right: 2rem">
    <button
      class="btn btn-sm btn-outline-secondary py-0 px-2"
      :disabled="!hasPrev || busy"
      title="Попередній запис"
      @click="$emit('prev')"
    >
      ‹
    </button>
    <span
      class="text-muted small font-monospace"
      style="min-width: 4rem; text-align: center"
    >
      <span
        v-if="busy"
        class="spinner-border spinner-border-sm"
        style="width: 0.7rem; height: 0.7rem"
      ></span>
      <template v-else>{{ position ?? '—' }} / {{ totalCount }}</template>
    </span>
    <button
      class="btn btn-sm btn-outline-secondary py-0 px-2"
      :disabled="!hasNext || busy"
      title="Наступний запис"
      @click="$emit('next')"
    >
      ›
    </button>
  </div>
</template>

<script setup>
defineProps({
  position: Number,
  totalCount: Number,
  hasPrev: Boolean,
  hasNext: Boolean,
  busy: Boolean,
})

defineEmits(['prev', 'next'])
</script>
