// frontend/src/components/BaseModal.vue
<template>
  <Teleport to="body">
    <!-- Backdrop только для floating режима -->
    <div
      v-if="visible && mode === 'floating'"
      class="modal-backdrop-simple"
      @click="handleBackdropClick"
    ></div>

    <!-- Модальное окно -->
    <div
      v-if="visible"
      ref="modalRef"
      class="modal-window"
      :class="[
        `modal-window--${mode}`,
        cursorClass,
      ]"
      :style="mode === 'floating' ? floatingStyle : mode === 'docked-right' ? dockedRightStyle : dockedBottomStyle"
    >
      <!-- Resize handle для docked режимов -->
      <div
        v-if="mode === 'docked-right'"
        class="resize-handle resize-handle--left"
        @mousedown="startResize"
      ></div>
      <div
        v-if="mode === 'docked-bottom'"
        class="resize-handle resize-handle--top"
        @mousedown="startResize"
      ></div>

      <div class="card shadow h-100 d-flex flex-column" style="overflow:hidden; border-radius: 0;">
        <div
          :class="[
            'card-header d-flex justify-content-between align-items-center py-2 px-4',
            headerClass,
            isDraggable ? 'cursor-grab' : ''
          ]"
          @mousedown="isDraggable && modalRef ? startDrag($event, modalRef) : null"
        >
          <h5 v-if="title" class="mb-0">{{ title }}</h5>
          <slot v-else name="title"></slot>

          <div class="d-flex gap-2 align-items-center">
            <button
              v-if="showModeSwitch"
              :class="['btn btn-sm', headerClass ? 'btn-light' : 'btn-outline-secondary']"
              @mousedown.stop
              @click="cycleMode"
              :title="getModeSwitchTitle()"
            >
              <i :class="getModeIcon()"></i>
            </button>
            <button
              :class="['btn btn-sm', headerClass ? 'btn-light' : 'btn-outline-secondary']"
              @mousedown.stop
              @click="handleClose"
            >
              ✕
            </button>
          </div>
        </div>

        <div class="card-body px-4 py-3" style="flex:1; overflow-y:auto;">
          <slot></slot>
        </div>

        <div v-if="$slots.footer" class="card-footer px-4 py-2 bg-light d-flex justify-content-between align-items-center">
          <slot name="footer"></slot>
        </div>
      </div>
    </div>
  </Teleport>
</template>

<script setup>
import { ref, watch, computed } from 'vue'
import { useModalWindow } from '../composables/useModalWindow'

const props = defineProps({
  visible: {
    type: Boolean,
    default: false
  },
  title: {
    type: String,
    default: ''
  },
  storageKey: {
    type: String,
    required: true
  },
  headerClass: {
    type: String,
    default: ''
  },
  defaultWidth: {
    type: Number,
    default: 700
  },
  minWidth: {
    type: Number,
    default: 500
  },
  maxWidth: {
    type: Number,
    default: 1200
  },
  defaultHeight: {
    type: Number,
    default: 400
  },
  minHeight: {
    type: Number,
    default: 300
  },
  maxHeight: {
    type: Number,
    default: 800
  },
  closeOnBackdrop: {
    type: Boolean,
    default: true
  },
  showModeSwitch: {
    type: Boolean,
    default: true
  }
})

const emit = defineEmits(['update:visible', 'close'])

const modalRef = ref(null)

// Modal window composable
const {
  mode,
  floatingStyle,
  dockedRightStyle,
  dockedBottomStyle,
  contentMargin,
  cursorClass,
  isDragging,
  isDraggable,
  startDrag,
  startResize,
  cycleMode,
} = useModalWindow({
  storageKey: props.storageKey,
  mode: 'floating',
  defaultWidth: props.defaultWidth,
  minWidth: props.minWidth,
  maxWidth: props.maxWidth,
  defaultHeight: props.defaultHeight,
  minHeight: props.minHeight,
  maxHeight: props.maxHeight,
})

// Отправляем событие об изменении margin для родительской страницы
watch([() => props.visible, contentMargin], () => {
  if (props.visible) {
    window.dispatchEvent(
      new CustomEvent('modal-content-margin-change', {
        detail: contentMargin.value,
      })
    )
  } else {
    // Сбрасываем margin при закрытии
    window.dispatchEvent(
      new CustomEvent('modal-content-margin-change', {
        detail: {},
      })
    )
  }
}, { deep: true })

function handleClose() {
  emit('update:visible', false)
  emit('close')
}

function handleBackdropClick() {
  if (props.closeOnBackdrop) {
    handleClose()
  }
}

function getModeIcon() {
  if (mode.value === 'floating') return 'bi bi-layout-sidebar-reverse'
  if (mode.value === 'docked-right') return 'bi bi-window-dock'
  if (mode.value === 'docked-bottom') return 'bi bi-window'
  return 'bi bi-window'
}

function getModeSwitchTitle() {
  if (mode.value === 'floating') return 'Закріпити справа'
  if (mode.value === 'docked-right') return 'Закріпити знизу'
  if (mode.value === 'docked-bottom') return 'Відкріпити (плаваюче вікно)'
  return 'Змінити режим'
}
</script>

<style scoped>
/* Backdrop для floating режима */
.modal-backdrop-simple {
  position: fixed;
  inset: 0;
  background: rgba(0, 0, 0, 0.5);
  z-index: 1049;
}

/* Базовые стили модального окна */
.modal-window {
  position: fixed;
  z-index: 1050;
}

/* Floating режим */
.modal-window--floating {
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  max-width: 1100px;
  max-height: 88vh;
  height: 88vh;
  width: 90vw;
}

/* Docked right */
.modal-window--docked-right {
  top: 0;
  right: 0;
  bottom: 0;
  border-left: 1px solid #dee2e6;
  box-shadow: -2px 0 8px rgba(0, 0, 0, 0.08);
}

/* Docked bottom */
.modal-window--docked-bottom {
  left: 0;
  right: 0;
  bottom: 0;
  box-shadow: 0 -4px 20px rgba(0, 0, 0, 0.15);
}

/* Resize handles */
.resize-handle {
  position: absolute;
  background: transparent;
  z-index: 10;
  transition: background 0.2s;
}

.resize-handle--left {
  left: 0;
  top: 0;
  bottom: 0;
  width: 6px;
  cursor: ew-resize;
}

.resize-handle--top {
  top: 0;
  left: 0;
  right: 0;
  height: 6px;
  cursor: ns-resize;
}

.resize-handle:hover {
  background: rgba(13, 110, 253, 0.3);
}

.resize-handle:active {
  background: rgba(13, 110, 253, 0.5);
}

/* Курсоры */
.cursor-grab {
  cursor: grab;
  user-select: none;
}

.cursor-grabbing,
.cursor-grabbing * {
  cursor: grabbing !important;
  user-select: none;
}

.cursor-resizing-x,
.cursor-resizing-x * {
  cursor: ew-resize !important;
  user-select: none;
}

.cursor-resizing-y,
.cursor-resizing-y * {
  cursor: ns-resize !important;
  user-select: none;
}

.card {
  box-shadow: 0 4px 20px rgba(0, 0, 0, 0.15);
}
</style>

// frontend-react/src/components/BaseModal.tsx
import React, { useEffect, useRef } from 'react'
import { useModalWindow } from '@/hooks/useModalWindow'

interface BaseModalProps {
  visible: boolean
  onClose: () => void
  title: React.ReactNode
  children: React.ReactNode
  footer?: React.ReactNode
  subheader?: React.ReactNode
  storageKey?: string
  defaultWidth?: number
  defaultHeight?: number
  minWidth?: number
  maxWidth?: number
  minHeight?: number
  maxHeight?: number
  closeOnBackdrop?: boolean
}

export default function BaseModal({
  visible,
  onClose,
  title,
  children,
  footer,
  subheader,
  storageKey = 'modal-window-settings',
  defaultWidth = 700,
  defaultHeight = 500,
  minWidth = 400,
  maxWidth = 1200,
  minHeight = 300,
  maxHeight = 800,
  closeOnBackdrop = true,
}: BaseModalProps) {
  const modalRef = useRef<HTMLDivElement>(null)

  const {
    mode,
    floatingStyle,
    dockedRightStyle,
    dockedBottomStyle,
    contentMargin,
    cursorClass,
    isDragging,
    isResizing,
    isDraggable,
    startDrag,
    startResize,
    cycleMode,
  } = useModalWindow({
    storageKey,
    defaultWidth,
    defaultHeight,
    minWidth,
    maxWidth,
    minHeight,
    maxHeight,
  })

  // Emit margin change event for page layout
  useEffect(() => {
    if (visible) {
      window.dispatchEvent(new CustomEvent('modal-margin-change', { detail: contentMargin }))
    } else {
      window.dispatchEvent(new CustomEvent('modal-margin-change', { detail: {} }))
    }
  }, [visible, contentMargin])

  // Block body scroll when modal is open
  useEffect(() => {
    if (visible) {
      document.body.classList.add('modal-open')
    } else {
      document.body.classList.remove('modal-open')
    }
    return () => {
      document.body.classList.remove('modal-open')
    }
  }, [visible])

  // Escape key handler
  useEffect(() => {
    if (!visible) return

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose()
      }
    }

    document.addEventListener('keydown', handleEscape)
    return () => document.removeEventListener('keydown', handleEscape)
  }, [visible, onClose])

  if (!visible) return null

  const handleBackdropClick = (e: React.MouseEvent) => {
    if (closeOnBackdrop && e.target === e.currentTarget) {
      onClose()
    }
  }

  const handleHeaderMouseDown = (e: React.MouseEvent) => {
    if (isDraggable) {
      startDrag(e, modalRef.current)
    }
  }

  const handleResizeMouseDown = (e: React.MouseEvent) => {
    startResize(e, modalRef.current)
  }

  // Icon for mode toggle button
  const getModeIcon = () => {
    if (mode === 'floating') return 'bi-layout-sidebar-reverse'
    if (mode === 'docked-right') return 'bi-window-dock'
    return 'bi-window'
  }

  const getModeTitle = () => {
    if (mode === 'floating') return 'Закріпити справа'
    if (mode === 'docked-right') return 'Закріпити знизу'
    return 'Плаваюче вікно'
  }

  // Floating mode
  if (mode === 'floating') {
    return (
      <>
        <div
          className="modal-backdrop show"
          style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}
          onClick={handleBackdropClick}
        />
        <div className={`modal-floating ${cursorClass}`}>
          <div
            ref={modalRef}
            className="card shadow-lg modal-floating-content"
            style={floatingStyle || undefined}
          >
            {/* Header */}
            <div
              className={`card-header d-flex justify-content-between align-items-center py-2 px-3 ${isDraggable ? 'cursor-grab' : ''}`}
              onMouseDown={handleHeaderMouseDown}
            >
              <div className="flex-grow-1">{title}</div>
              <div className="d-flex gap-1">
                <button
                  className="btn btn-sm btn-outline-secondary"
                  onClick={cycleMode}
                  title={getModeTitle()}
                  style={{ padding: '2px 6px' }}
                >
                  <i className={`bi ${getModeIcon()}`} />
                </button>
                <button
                  className="btn btn-sm btn-outline-secondary"
                  onClick={onClose}
                  style={{ padding: '2px 6px' }}
                >
                  ✕
                </button>
              </div>
            </div>

            {/* Subheader (tabs) */}
            {subheader && (
              <div className="border-bottom px-2">
                {subheader}
              </div>
            )}

            {/* Body */}
            <div className="px-4 py-3" style={{ overflowY: 'auto', flex: 1 }}>
              {children}
            </div>

            {/* Footer */}
            {footer && (
              <div className="card-footer d-flex gap-2 justify-content-end py-2 px-3">
                {footer}
              </div>
            )}

            {/* Resize handle */}
            <div
              className="modal-resize-handle modal-resize-se"
              onMouseDown={handleResizeMouseDown}
              title="Змінити розмір"
            />
          </div>
        </div>
      </>
    )
  }

  // Docked right mode
  if (mode === 'docked-right') {
    return (
      <div className={`modal-docked-right ${cursorClass}`} style={dockedRightStyle || undefined}>
        <div ref={modalRef} className="card shadow-lg h-100 d-flex flex-column">
          {/* Header */}
          <div className="card-header d-flex justify-content-between align-items-center py-2 px-3">
            <div className="flex-grow-1">{title}</div>
            <div className="d-flex gap-1">
              <button
                className="btn btn-sm btn-outline-secondary"
                onClick={cycleMode}
                title={getModeTitle()}
                style={{ padding: '2px 6px' }}
              >
                <i className={`bi ${getModeIcon()}`} />
              </button>
              <button
                className="btn btn-sm btn-outline-secondary"
                onClick={onClose}
                style={{ padding: '2px 6px' }}
              >
                ✕
              </button>
            </div>
          </div>

          {/* Subheader */}
          {subheader && (
            <div className="border-bottom px-2">
              {subheader}
            </div>
          )}

          {/* Body */}
          <div className="px-4 py-3" style={{ overflowY: 'auto', flex: 1 }}>
            {children}
          </div>

          {/* Footer */}
          {footer && (
            <div className="card-footer d-flex gap-2 justify-content-end py-2 px-3">
              {footer}
            </div>
          )}
        </div>

        {/* Resize handle (left edge) */}
        <div
          className="modal-resize-handle modal-resize-w"
          onMouseDown={handleResizeMouseDown}
          title="Змінити ширину"
        />
      </div>
    )
  }

  // Docked bottom mode
  return (
    <div className={`modal-docked-bottom ${cursorClass}`} style={dockedBottomStyle || undefined}>
      <div ref={modalRef} className="card shadow-lg h-100 d-flex flex-column">
        {/* Header */}
        <div className="card-header d-flex justify-content-between align-items-center py-2 px-3">
          <div className="flex-grow-1">{title}</div>
          <div className="d-flex gap-1">
            <button
              className="btn btn-sm btn-outline-secondary"
              onClick={cycleMode}
              title={getModeTitle()}
              style={{ padding: '2px 6px' }}
            >
              <i className={`bi ${getModeIcon()}`} />
            </button>
            <button
              className="btn btn-sm btn-outline-secondary"
              onClick={onClose}
              style={{ padding: '2px 6px' }}
            >
              ✕
            </button>
          </div>
        </div>

        {/* Subheader */}
        {subheader && (
          <div className="border-bottom px-2">
            {subheader}
          </div>
        )}

        {/* Body */}
        <div className="px-4 py-3" style={{ overflowY: 'auto', flex: 1 }}>
          {children}
        </div>

        {/* Footer */}
        {footer && (
          <div className="card-footer d-flex gap-2 justify-content-end py-2 px-3">
            {footer}
          </div>
        )}
      </div>

      {/* Resize handle (top edge) */}
      <div
        className="modal-resize-handle modal-resize-n"
        onMouseDown={handleResizeMouseDown}
        title="Змінити висоту"
      />
    </div>
  )
}
