// frontend/src/components/EmptyState.vue
<!-- Copyright (c) 2026 Oleksandr Nosov. MIT License. -->
<template>
  <div class="text-center py-5">
    <i :class="['bi', filtered ? 'bi-funnel' : icon]" style="font-size:2.5rem; opacity:.35"></i>

    <p class="text-muted mt-3 mb-3">
      <template v-if="filtered">За вибраними фільтрами нічого не знайдено</template>
      <template v-else>Ще немає {{ entityLabel }}</template>
    </p>

    <button v-if="filtered" class="btn btn-sm btn-outline-secondary" @click="$emit('reset-filters')">
      <i class="bi bi-x-circle me-1"></i>Скинути фільтри
    </button>
    <button v-else-if="canCreate" class="btn btn-sm btn-primary" @click="$emit('create')">
      <i class="bi bi-plus-lg me-1"></i>Створити
    </button>
  </div>
</template>

<script setup>
/**
 * Порожній список. Два стани, які раніше зливались в одне «Немає даних»:
 * записів справді немає (тоді пропонуємо створити) — і фільтр нічого не знайшов
 * (тоді пропонуємо його скинути). Друге легко сплутати з першим, бо фільтр
 * відновлюється з URL і переживає перезавантаження сторінки.
 */
defineProps({
  /** Чи застосовано зараз хоч один фільтр (рахує той, хто рендерить) */
  filtered: { type: Boolean, default: false },
  /** Родовий відмінок множини: «населених пунктів», «користувачів» */
  entityLabel: { type: String, default: 'записів' },
  canCreate: { type: Boolean, default: false },
  icon: { type: String, default: 'bi-inbox' },
})
defineEmits(['create', 'reset-filters'])
</script>

// frontend-react/src/components/EmptyState.tsx
interface EmptyStateProps {
  /** Чи застосовано зараз хоч один фільтр (рахує той, хто рендерить) */
  filtered?: boolean
  /** Родовий відмінок множини: «населених пунктів», «користувачів» */
  entityLabel?: string
  canCreate?: boolean
  icon?: string
  onCreate?: () => void
  onResetFilters?: () => void
}

/**
 * Порожній список. Два стани, які раніше зливались в одне «Немає даних»:
 * записів справді немає (тоді пропонуємо створити) — і фільтр нічого не знайшов
 * (тоді пропонуємо його скинути). Дзеркало Vue: components/EmptyState.vue.
 */
export default function EmptyState({
  filtered = false,
  entityLabel = 'записів',
  canCreate = false,
  icon = 'bi-inbox',
  onCreate,
  onResetFilters,
}: EmptyStateProps) {
  return (
    <div className="text-center py-5">
      <i className={`bi ${filtered ? 'bi-funnel' : icon}`} style={{ fontSize: '2.5rem', opacity: 0.35 }} />

      <p className="text-muted mt-3 mb-3">
        {filtered ? 'За вибраними фільтрами нічого не знайдено' : `Ще немає ${entityLabel}`}
      </p>

      {filtered ? (
        <button className="btn btn-sm btn-outline-secondary" onClick={onResetFilters}>
          <i className="bi bi-x-circle me-1" />Скинути фільтри
        </button>
      ) : canCreate ? (
        <button className="btn btn-sm btn-primary" onClick={onCreate}>
          <i className="bi bi-plus-lg me-1" />Створити
        </button>
      ) : null}
    </div>
  )
}
