// frontend/src/components/LanguageSwitcher.vue
<template>
  <div class="dropdown">
    <button
      class="btn btn-sm btn-link text-decoration-none dropdown-toggle"
      type="button"
      data-bs-toggle="dropdown"
      aria-expanded="false"
      :title="t('language.selectLanguage')"
    >
      <i class="bi bi-translate me-1"></i>
      {{ currentLocaleName }}
    </button>
    <ul class="dropdown-menu dropdown-menu-end">
      <li v-for="loc in availableLocales" :key="loc.code">
        <a
          class="dropdown-item"
          :class="{ active: locale === loc.code }"
          href="#"
          @click.prevent="changeLocale(loc.code)"
        >
          {{ loc.name }}
        </a>
      </li>
    </ul>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { availableLocales } from '@/locales'

const { locale, t } = useI18n()

const currentLocaleName = computed(() => {
  const current = availableLocales.find(l => l.code === locale.value)
  return current ? current.name : 'UK'
})

function changeLocale(newLocale) {
  locale.value = newLocale
  localStorage.setItem('admin.locale', newLocale)
  document.documentElement.lang = newLocale
}
</script>

// frontend-react/src/components/LanguageSwitcher.tsx
import { useTranslation } from 'react-i18next'
import { availableLocales } from '@locales'

export default function LanguageSwitcher() {
  const { i18n, t } = useTranslation()

  const currentLocaleName = availableLocales.find(l => l.code === i18n.language)?.name || 'UK'

  function changeLocale(newLocale: string) {
    i18n.changeLanguage(newLocale)
    localStorage.setItem('admin.locale', newLocale)
    document.documentElement.lang = newLocale
  }

  return (
    <div className="dropdown">
      <button
        className="btn btn-sm btn-link text-decoration-none dropdown-toggle"
        type="button"
        data-bs-toggle="dropdown"
        aria-expanded="false"
        title={t('language.selectLanguage')}
      >
        <i className="bi bi-translate me-1"></i>
        {currentLocaleName}
      </button>
      <ul className="dropdown-menu dropdown-menu-end">
        {availableLocales.map(loc => (
          <li key={loc.code}>
            <a
              className={`dropdown-item ${i18n.language === loc.code ? 'active' : ''}`}
              href="#"
              onClick={(e) => {
                e.preventDefault()
                changeLocale(loc.code)
              }}
            >
              {loc.name}
            </a>
          </li>
        ))}
      </ul>
    </div>
  )
}
