// frontend/src/components/TableSkeleton.vue
<!-- Copyright (c) 2026 Oleksandr Nosov. MIT License. -->
<template>
  <tbody>
    <tr v-for="r in rows" :key="r">
      <td v-if="hasCheckbox" style="width:36px">
        <span class="sk" style="width:1rem"></span>
      </td>
      <td v-if="hasExpand" style="width:32px">
        <span class="sk" style="width:1rem"></span>
      </td>
      <td
        v-for="(col, i) in columns"
        :key="i"
        :style="col.width ? `width:${col.width}px` : ''"
        :class="col.align === 'end' ? 'text-end' : ''"
      >
        <span class="sk" :style="{ width: col.skeletonWidth ?? '80%' }"></span>
      </td>
    </tr>
  </tbody>
</template>

<script setup>
defineProps({
  rows: { type: Number, default: 10 },
  columns: { type: Array, required: true },
  hasCheckbox: { type: Boolean, default: false },
  hasExpand: { type: Boolean, default: false },
})
</script>

<style scoped>
.sk {
  display: inline-block;
  height: 0.85rem;
  border-radius: 0.2rem;
  background: var(--bs-tertiary-bg);
  animation: sk-pulse 1.2s ease-in-out infinite;
}
@keyframes sk-pulse {
  0%,
  100% {
    opacity: 1;
  }
  50% {
    opacity: 0.45;
  }
}
@media (prefers-reduced-motion: reduce) {
  .sk {
    animation: none;
  }
}
</style>

// frontend-react/src/components/TableSkeleton.tsx
interface Column {
  width?: number
  align?: 'left' | 'right'
  skeletonWidth?: string
}

interface TableSkeletonProps {
  rows?: number
  columns: Column[]
  hasCheckbox?: boolean
  hasExpand?: boolean
}

export default function TableSkeleton({
  rows = 10,
  columns,
  hasCheckbox = false,
  hasExpand = false,
}: TableSkeletonProps) {
  return (
    <tbody>
      {Array.from({ length: rows }, (_, r) => (
        <tr key={r}>
          {hasCheckbox && (
            <td style={{ width: '36px' }}>
              <span className="sk" style={{ width: '1rem' }} />
            </td>
          )}
          {hasExpand && (
            <td style={{ width: '32px' }}>
              <span className="sk" style={{ width: '1rem' }} />
            </td>
          )}
          {columns.map((col, i) => (
            <td
              key={i}
              style={col.width ? { width: `${col.width}px` } : undefined}
              className={col.align === 'right' ? 'text-end' : ''}
            >
              <span className="sk" style={{ width: col.skeletonWidth ?? '80%' }} />
            </td>
          ))}
        </tr>
      ))}
      <style>{`
        .sk {
          display: inline-block;
          height: 0.85rem;
          border-radius: 0.2rem;
          background: var(--bs-tertiary-bg);
          animation: sk-pulse 1.2s ease-in-out infinite;
        }
        @keyframes sk-pulse {
          0%, 100% { opacity: 1; }
          50% { opacity: 0.45; }
        }
        @media (prefers-reduced-motion: reduce) {
          .sk { animation: none; }
        }
      `}</style>
    </tbody>
  )
}
