// frontend/src/components/TopNav.vue
<template>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark px-3 py-0">
    <!-- Brand -->
    <router-link class="navbar-brand fw-bold me-4" to="/">
      Oleksandr Nosov <span class="text-secondary fw-normal small">Admin</span>
    </router-link>

    <!-- Top-level menu items -->
    <div class="collapse navbar-collapse">
      <ul class="navbar-nav me-auto">
        <li
          v-for="section in visibleMenu"
          :key="section.id"
          class="nav-item dropdown"
          @mouseenter="openMenu = section.id"
          @mouseleave="openMenu = null"
        >
          <a
            class="nav-link dropdown-toggle px-3 py-3"
            :class="{ active: activeSection === section.id }"
            href="#"
            @click.prevent="openMenu = openMenu === section.id ? null : section.id"
          >
            <i :class="['bi', section.icon, 'me-1']"></i>
            {{ section.label }}
          </a>
          <!-- Second level -->
          <ul
            class="dropdown-menu mt-0"
            :class="{ show: openMenu === section.id }"
          >
            <li v-for="item in section.items.filter(i => auth.can(i.permission))" :key="item.to">
              <router-link
                class="dropdown-item"
                :to="item.to"
                @click="openMenu = null"
              >
                <i :class="['bi', item.icon, 'me-2', 'text-muted']"></i>
                {{ item.label }}
              </router-link>
            </li>
          </ul>
        </li>
      </ul>

      <!-- User block -->
      <div class="d-flex align-items-center gap-3">
        <!-- Theme toggle -->
        <button
          type="button"
          class="btn btn-sm btn-outline-secondary"
          :title="themeTitle"
          @click="theme.cycle"
        >
          <i class="bi" :class="themeIcon"></i>
        </button>

        <!-- Language switcher -->
        <LanguageSwitcher />

        <div class="dropdown">
          <button
            class="btn btn-sm btn-outline-secondary dropdown-toggle"
            type="button"
            @click="userMenuOpen = !userMenuOpen"
          >
            <i class="bi bi-person-circle me-1"></i>
            {{ auth.user.value?.name }}
          </button>
          <ul class="dropdown-menu dropdown-menu-end" :class="{ show: userMenuOpen }">
            <li>
              <router-link class="dropdown-item" to="/change-password" @click="userMenuOpen = false">
                <i class="bi bi-key me-2"></i>Змінити пароль
              </router-link>
            </li>
            <li><hr class="dropdown-divider"></li>
            <li>
              <a class="dropdown-item" href="#" @click.prevent="doLogout">
                <i class="bi bi-box-arrow-right me-2"></i>Вийти
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</template>

<script setup>
import { ref, computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuth } from '@/composables/useAuth'
import { useTheme } from '@/composables/useTheme'
import LanguageSwitcher from './LanguageSwitcher.vue'
import menu from '@/config/menu.json'
import { findMenuLocation } from '@/utils/menuLocation'

const auth   = useAuth()
const theme  = useTheme()
const route  = useRoute()
const router = useRouter()

const openMenu = ref(null)
const userMenuOpen = ref(false)

const visibleMenu = computed(() =>
  menu.filter(s => auth.can(s.permission))
)

// Через findMenuLocation, а не голий startsWith: `/sto-managers` збігався б із
// `/sto` і підсвічував чужий розділ (див. utils/menuLocation.js).
const activeSection = computed(() => findMenuLocation(route.path)?.section.id ?? null)

const themeIcon = computed(() => {
  if (theme.mode.value === 'light') return 'bi-sun-fill'
  if (theme.mode.value === 'dark') return 'bi-moon-stars-fill'
  return 'bi-circle-half'
})

const themeTitle = computed(() => {
  if (theme.mode.value === 'light') return 'Світла тема'
  if (theme.mode.value === 'dark') return 'Темна тема'
  return 'Авто (за системою)'
})

async function doLogout() {
  auth.logout()
  await router.push('/login')
}
</script>

// frontend-react/src/components/TopNav.tsx
import { useState } from 'react'
import { Link, useLocation, useNavigate } from 'react-router-dom'
import { useAuth } from '@/contexts/AuthContext'
import { useTheme } from '@/composables/useTheme'
import LanguageSwitcher from './LanguageSwitcher'
import menuConfig from '@/config/menu.json'
import { findMenuLocation } from '@/utils/menuLocation'

interface MenuItem {
  label: string
  to: string
  icon: string
  permission: string
  roles: string[]
}

interface MenuSection {
  id: string
  label: string
  icon: string
  permission: string
  roles: string[]
  items: MenuItem[]
}

export default function TopNav() {
  const { user, logout, can } = useAuth()
  const { mode, cycle } = useTheme()
  const location = useLocation()
  const navigate = useNavigate()
  const [openMenu, setOpenMenu] = useState<string | null>(null)
  const [userMenuOpen, setUserMenuOpen] = useState(false)

  const menu = menuConfig as MenuSection[]

  // Розділ показуємо, якщо є право на нього або хоча б на один його пункт —
  // інакше заголовок групи висів би з порожнім списком.
  const visibleMenu = menu.filter(
    s => can(s.permission) || s.items.some(i => can(i.permission))
  )

  // Через findMenuLocation, а не голий startsWith: `/sto-managers` збігався б із
  // `/sto` і підсвічував чужий розділ (див. utils/menuLocation.ts).
  const activeSection = findMenuLocation(location.pathname)?.section.id ?? null

  const themeIcon = mode === 'light' ? 'bi-sun-fill' : mode === 'dark' ? 'bi-moon-stars-fill' : 'bi-circle-half'
  const themeTitle = mode === 'light' ? 'Світла тема' : mode === 'dark' ? 'Темна тема' : 'Авто (за системою)'

  const handleLogout = async () => {
    logout()
    navigate('/login')
  }

  return (
    <nav className="navbar navbar-expand-lg navbar-dark bg-dark px-3 py-0">
      {/* Brand */}
      <Link className="navbar-brand fw-bold me-4" to="/">
        Oleksandr Nosov <span className="text-secondary fw-normal small">Admin (React)</span>
      </Link>

      {/* Top-level menu items */}
      <div className="collapse navbar-collapse">
        <ul className="navbar-nav me-auto">
          {visibleMenu.map(section => (
            <li
              key={section.id}
              className="nav-item dropdown"
              onMouseEnter={() => setOpenMenu(section.id)}
              onMouseLeave={() => setOpenMenu(null)}
            >
              <a
                className={`nav-link dropdown-toggle px-3 py-3 ${
                  activeSection === section.id ? 'active' : ''
                }`}
                href="#"
                onClick={(e) => {
                  e.preventDefault()
                  setOpenMenu(openMenu === section.id ? null : section.id)
                }}
              >
                <i className={`bi ${section.icon} me-1`}></i>
                {section.label}
              </a>
              {/* Second level */}
              <ul className={`dropdown-menu mt-0 ${openMenu === section.id ? 'show' : ''}`}>
                {section.items.filter(i => can(i.permission)).map(item => (
                  <li key={item.to}>
                    <Link
                      className="dropdown-item"
                      to={item.to}
                      onClick={() => setOpenMenu(null)}
                    >
                      <i className={`bi ${item.icon} me-2 text-muted`}></i>
                      {item.label}
                    </Link>
                  </li>
                ))}
              </ul>
            </li>
          ))}
        </ul>

        {/* User block */}
        <div className="d-flex align-items-center gap-3">
          {/* Theme toggle */}
          <button
            type="button"
            className="btn btn-sm btn-outline-secondary"
            title={themeTitle}
            onClick={cycle}
          >
            <i className={`bi ${themeIcon}`}></i>
          </button>

          {/* Language switcher */}
          <LanguageSwitcher />

          <div className="dropdown">
            <button
              className="btn btn-sm btn-outline-secondary dropdown-toggle"
              type="button"
              onClick={() => setUserMenuOpen(!userMenuOpen)}
            >
              <i className="bi bi-person-circle me-1"></i>
              {user?.username || 'User'}
            </button>
            <ul className={`dropdown-menu dropdown-menu-end ${userMenuOpen ? 'show' : ''}`}>
              <li>
                <Link
                  className="dropdown-item"
                  to="/change-password"
                  onClick={() => setUserMenuOpen(false)}
                >
                  <i className="bi bi-key me-2"></i>Змінити пароль
                </Link>
              </li>
              <li><hr className="dropdown-divider" /></li>
              <li>
                <a className="dropdown-item" href="#" onClick={handleLogout}>
                  <i className="bi bi-box-arrow-right me-2"></i>Вийти
                </a>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </nav>
  )
}
