// frontend-react/src/list-framework/cells/BadgeCell.tsx
import type { CellProps } from '../types'

/**
 * Значення як кольоровий бейдж. `options` дають підпис (як у select),
 * `variants` — колір Bootstrap на значення; без збігу — `secondary`.
 * Редагування немає: це подання, а не ввід (для вибору зі списку є `select`).
 * Дзеркало Vue: cells/BadgeCell.vue.
 */
export default function BadgeCell({ field, value }: CellProps) {
  if (value === null || value === undefined || value === '') {
    return <span className="text-muted">{field.emptyLabel ?? '—'}</span>
  }

  const found = (field.options ?? []).find(o => String(o.value) === String(value))
  const variant = field.variants?.[String(value)] ?? field.variant ?? 'secondary'

  return <span className={`badge bg-${variant}`}>{found ? found.label : String(value)}</span>
}

// frontend/src/list-framework/cells/BadgeCell.vue
<!-- Copyright (c) 2026 Oleksandr Nosov. MIT License. -->
<template>
  <span v-if="modelValue !== null && modelValue !== undefined && modelValue !== ''" class="badge" :class="`bg-${variant}`">
    {{ label }}
  </span>
  <span v-else class="text-muted">{{ field.emptyLabel ?? '—' }}</span>
</template>

<script setup>
import { computed } from 'vue'

/**
 * Значення як кольоровий бейдж. `options` дають підпис (як у select),
 * `variants` — колір Bootstrap на значення; без збігу — `secondary`.
 * Редагування немає: це подання, а не ввід (для вибору зі списку є `select`).
 */
const props = defineProps({
  field: { type: Object, required: true },
  modelValue: { type: [String, Number, Boolean], default: null },
  readonly: { type: Boolean, default: true },
  row: { type: Object, default: () => ({}) },
})
defineEmits(['update:modelValue'])

const label = computed(() => {
  const found = (props.field.options ?? []).find((o) => String(o.value) === String(props.modelValue))
  return found ? found.label : props.modelValue
})

const variant = computed(
  () => props.field.variants?.[props.modelValue] ?? props.field.variant ?? 'secondary'
)
</script>
