// frontend-react/src/list-framework/cells/TextCell.tsx
import type { CellProps } from '../types'

export default function TextCell({ field, value, readonly, onChange }: CellProps) {
  if (readonly) {
    // maxWidth: довгий текст (повідомлення, опис) обрізається, повний — у title.
    // Дзеркало Vue: cells/TextCell.vue.
    if (field.maxWidth) {
      return (
        <div className="text-truncate" style={{ maxWidth: field.maxWidth }} title={value ?? ''}>
          {value ?? field.emptyLabel ?? '—'}
        </div>
      )
    }
    return <span>{value ?? field.emptyLabel ?? '—'}</span>
  }

  return (
    <input
      defaultValue={value ?? ''}
      type="text"
      className="form-control form-control-sm"
      onBlur={(e) => {
        if (e.target.value !== (value ?? '')) onChange(e.target.value)
      }}
      onKeyDown={(e) => {
        if (e.key === 'Enter') e.currentTarget.blur()
        if (e.key === 'Escape') {
          e.currentTarget.value = value ?? ''
          e.currentTarget.blur()
        }
      }}
    />
  )
}

// frontend/src/list-framework/cells/TextCell.vue
<!-- Copyright (c) 2026 Oleksandr Nosov. MIT License. -->
<template>
  <!-- maxWidth: довгий текст (повідомлення, опис) обрізається, повний — у title -->
  <div
    v-if="readonly && field.maxWidth"
    class="text-truncate"
    :style="{ maxWidth: field.maxWidth }"
    :title="modelValue ?? ''"
  >{{ modelValue ?? field.emptyLabel ?? '—' }}</div>
  <span v-else-if="readonly">{{ modelValue ?? field.emptyLabel ?? '—' }}</span>
  <input
    v-else
    :value="modelValue"
    type="text"
    class="form-control form-control-sm"
    @change="$emit('update:modelValue', $event.target.value)"
  />
</template>

<script setup>
defineProps({
  field: { type: Object, required: true },
  modelValue: { type: [String, Number], default: null },
  readonly: { type: Boolean, default: true },
  row: { type: Object, default: () => ({}) },
})
defineEmits(['update:modelValue'])
</script>
