// frontend/src/list-framework/cells/BooleanCell.vue
<template>
  <span v-if="readonly" class="badge" :class="modelValue ? 'bg-success' : 'bg-danger'">
    {{ modelValue ? (field.trueLabel ?? 'Так') : (field.falseLabel ?? 'Ні') }}
  </span>
  <button
    v-else
    type="button"
    class="badge border-0 btn p-1"
    :class="modelValue ? 'bg-success' : 'bg-danger'"
    @click="$emit('update:modelValue', !modelValue)"
  >
    {{ modelValue ? (field.trueLabel ?? 'Так') : (field.falseLabel ?? 'Ні') }}
  </button>
</template>

<script setup>
defineProps({
  field: { type: Object, required: true },
  modelValue: { type: Boolean, default: false },
  readonly: { type: Boolean, default: true },
  row: { type: Object, default: () => ({}) },
})
defineEmits(['update:modelValue'])
</script>

// frontend-react/src/list-framework/cells/BooleanCell.tsx
import type { CellProps } from '../types'

export default function BooleanCell({ field, value, readonly, onChange }: CellProps) {
  const label = value ? (field.trueLabel ?? 'Так') : (field.falseLabel ?? 'Ні')
  const color = value ? 'bg-success' : 'bg-danger'

  if (readonly) {
    return <span className={`badge ${color}`}>{label}</span>
  }

  return (
    <button
      type="button"
      className={`badge border-0 btn p-1 ${color}`}
      onClick={() => onChange(!value)}
    >
      {label}
    </button>
  )
}
