// frontend/src/list-framework/cells/DateTimeCell.vue
<!-- Copyright (c) 2026 Oleksandr Nosov. MIT License. -->
<template>
  <span class="text-muted" style="white-space:nowrap">{{ text }}</span>
</template>

<script setup>
import { computed } from 'vue'
import { formatDate, formatDateShort } from '@/utils/date'

// Дати ніде не редагуються інлайн — комірка завжди readonly (проп приймається
// заради єдиного інтерфейсу з рештою типів). `dateOnly: true` — без часу.
const props = defineProps({
  field: { type: Object, required: true },
  modelValue: { type: [String, Number, Date], default: null },
  readonly: { type: Boolean, default: true },
  row: { type: Object, default: () => ({}) },
})
defineEmits(['update:modelValue'])

const text = computed(() =>
  props.field.dateOnly ? formatDateShort(props.modelValue) : formatDate(props.modelValue)
)
</script>

// frontend-react/src/list-framework/cells/DateTimeCell.tsx
import { formatDate, formatDateShort } from '@/utils/date'
import type { CellProps } from '../types'

/**
 * Дати ніде не редагуються інлайн — комірка завжди readonly (проп приймається
 * заради єдиного інтерфейсу з рештою типів). `dateOnly: true` — без часу.
 * Дзеркало Vue: cells/DateTimeCell.vue.
 */
export default function DateTimeCell({ field, value }: CellProps) {
  return (
    <span className="text-muted" style={{ whiteSpace: 'nowrap' }}>
      {field.dateOnly ? formatDateShort(value) : formatDate(value)}
    </span>
  )
}
