// frontend-react/src/pages/AnalyticsStats.tsx
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import TrendChart from '@/components/charts/TrendChart'
import { apiGet } from '@/utils/api'
import {
  BOT_CATEGORY_BADGE,
  BOT_CATEGORY_LABELS,
  BOT_CATEGORY_PROGRESS,
  CLIENT_TYPE_BADGE,
  CLIENT_TYPE_PROGRESS,
  DEVICE_ICON,
  DEVICE_NAME,
  buildTrafficTrend,
  clientTypeLabel,
  responseTimeClass,
  shortUrl,
} from './analyticsLabels'

export default function AnalyticsStats() {
  const [stats, setStats] = useState<any>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [days, setDays] = useState(7)
  const [section, setSection] = useState('')

  const load = useCallback(async () => {
    setLoading(true)
    setError('')

    const params = new URLSearchParams({ days: String(days) })
    if (section) params.set('section', section)

    try {
      const res = await apiGet(`/admin/analytics/stats?${params}`)
      setStats(res.data)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Помилка завантаження')
    } finally {
      setLoading(false)
    }
  }, [days, section])

  useEffect(() => { load() }, [load])

  const botsCount = (stats?.bots_vs_real ?? []).find((i: any) => i.is_bot === 1)?.count ?? 0
  const botsPercent = stats?.total ? Math.round((botsCount / stats.total) * 100) : 0
  const trend = buildTrafficTrend(stats?.trend)

  const pctOfTotal = (count: number) => (stats?.total ? Math.round((count / stats.total) * 100) : 0)
  const pctOfBots = (count: number) => (botsCount ? Math.round((count / botsCount) * 100) : 0)

  return (
    <div>
      <div className="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
        <div className="d-flex align-items-center gap-2">
          <Link to="/analytics" className="btn btn-sm btn-outline-secondary">
            <i className="bi bi-arrow-left" /> Назад
          </Link>
          <h5 className="mb-0">Статистика відвідувань</h5>
        </div>
        <div className="d-flex gap-2">
          <select
            value={section}
            onChange={(e) => setSection(e.target.value)}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            <option value="">Всі розділи</option>
            <option value="frontend">Frontend</option>
            <option value="admin">Адмінка</option>
          </select>
          <select
            value={days}
            onChange={(e) => setDays(Number(e.target.value))}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            <option value={1}>За 24 години</option>
            {[7, 14, 30, 60, 90].map(d => <option key={d} value={d}>За {d} днів</option>)}
          </select>
        </div>
      </div>

      {loading && (
        <div className="text-center py-5">
          <div className="spinner-border text-primary" />
        </div>
      )}

      {!loading && error && <div className="alert alert-danger">{error}</div>}

      {!loading && !error && stats && (
        <div className="row g-3">
          {/* Зведення */}
          <div className="col-md-3">
            <div className="card text-center shadow-sm">
              <div className="card-body">
                <h6 className="text-muted mb-2">Всього переглядів</h6>
                <h2 className="mb-0">{stats.total}</h2>
                <small className="text-muted">за {stats.period_days} днів</small>
              </div>
            </div>
          </div>

          <div className="col-md-3">
            <div className="card text-center shadow-sm">
              <div className="card-body">
                <h6 className="text-muted mb-2">Унікальні відвідувачі</h6>
                <h2 className="mb-0">{stats.unique_visitors}</h2>
                <small className="text-muted">по IP (без ботів)</small>
              </div>
            </div>
          </div>

          <div className="col-md-3">
            <div className="card text-center shadow-sm">
              <div className="card-body">
                <h6 className="text-muted mb-2">Середній час відповіді</h6>
                <h2 className={`mb-0 ${responseTimeClass(stats.response_time?.avg_time)}`}>
                  {Math.round(stats.response_time?.avg_time || 0)}ms
                </h2>
                <small className="text-muted">макс: {stats.response_time?.max_time}ms</small>
              </div>
            </div>
          </div>

          <div className="col-md-3">
            <div className="card text-center shadow-sm">
              <div className="card-body">
                <h6 className="text-muted mb-2">Боти</h6>
                <h2 className="mb-0">{botsCount}</h2>
                <small className="text-muted">{botsPercent}% трафіку</small>
              </div>
            </div>
          </div>

          {/* Топ сторінок */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Топ-10 сторінок</strong></div>
              <div className="card-body">
                <table className="table table-sm table-hover mb-0">
                  <thead><tr><th>URL</th><th className="text-end">Перегляди</th></tr></thead>
                  <tbody>
                    {(stats.top_pages ?? []).map((item: any) => (
                      <tr key={item.path}>
                        <td><code className="small">{item.path}</code></td>
                        <td className="text-end"><strong>{item.views}</strong></td>
                      </tr>
                    ))}
                    {!stats.top_pages?.length && (
                      <tr><td colSpan={2} className="text-center text-muted py-3">Немає даних</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Топ джерел */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Топ-10 джерел</strong></div>
              <div className="card-body">
                <table className="table table-sm table-hover mb-0">
                  <thead><tr><th>Referer</th><th className="text-end">К-сть</th></tr></thead>
                  <tbody>
                    {(stats.top_referers ?? []).map((item: any) => (
                      <tr key={item.referer}>
                        <td className="small text-truncate" style={{ maxWidth: '300px' }}>{shortUrl(item.referer)}</td>
                        <td className="text-end"><strong>{item.count}</strong></td>
                      </tr>
                    ))}
                    {!stats.top_referers?.length && (
                      <tr><td colSpan={2} className="text-center text-muted py-3">Немає даних</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Пристрої */}
          <div className="col-md-4">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>По пристроях</strong></div>
              <div className="card-body">
                {(stats.by_device ?? []).map((item: any) => (
                  <div key={item.device_type} className="d-flex justify-content-between align-items-center mb-2">
                    <span>
                      <i className={`bi ${DEVICE_ICON[item.device_type] ?? 'bi-question'}`} />{' '}
                      {DEVICE_NAME[item.device_type] ?? item.device_type}
                    </span>
                    <strong>{item.count}</strong>
                  </div>
                ))}
                {!stats.by_device?.length && <div className="text-center text-muted py-3">Немає даних</div>}
              </div>
            </div>
          </div>

          {/* Браузери */}
          <div className="col-md-4">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>По браузерах</strong></div>
              <div className="card-body">
                {(stats.by_browser ?? []).map((item: any) => (
                  <div key={item.browser} className="d-flex justify-content-between align-items-center mb-2">
                    <span>{item.browser}</span>
                    <strong>{item.count}</strong>
                  </div>
                ))}
                {!stats.by_browser?.length && <div className="text-center text-muted py-3">Немає даних</div>}
              </div>
            </div>
          </div>

          {/* ОС */}
          <div className="col-md-4">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>По ОС</strong></div>
              <div className="card-body">
                {(stats.by_os ?? []).map((item: any) => (
                  <div key={item.os} className="d-flex justify-content-between align-items-center mb-2">
                    <span>{item.os}</span>
                    <strong>{item.count}</strong>
                  </div>
                ))}
                {!stats.by_os?.length && <div className="text-center text-muted py-3">Немає даних</div>}
              </div>
            </div>
          </div>

          {/* Типи клієнтів */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>По типах клієнтів</strong></div>
              <div className="card-body">
                {(stats.by_client_type ?? []).map((item: any) => (
                  <div key={item.client_type} className="d-flex justify-content-between align-items-center mb-2">
                    <span
                      className={CLIENT_TYPE_BADGE[item.client_type] ?? 'badge bg-light text-dark'}
                      style={{ minWidth: '140px' }}
                    >
                      {clientTypeLabel(item.client_type)}
                    </span>
                    <div className="flex-grow-1 mx-3">
                      <div className="progress" style={{ height: '20px' }}>
                        <div
                          className={`progress-bar ${CLIENT_TYPE_PROGRESS[item.client_type] ?? 'bg-light'}`}
                          style={{ width: `${pctOfTotal(item.count)}%` }}
                        >
                          {pctOfTotal(item.count)}%
                        </div>
                      </div>
                    </div>
                    <strong style={{ minWidth: '60px', textAlign: 'right' }}>{item.count}</strong>
                  </div>
                ))}
                {!stats.by_client_type?.length && <div className="text-center text-muted py-3">Немає даних</div>}
              </div>
            </div>
          </div>

          {/* Категорії ботів */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Категорії ботів</strong></div>
              <div className="card-body">
                {(stats.bot_categories ?? []).map((item: any) => (
                  <div key={item.bot_category} className="d-flex justify-content-between align-items-center mb-2">
                    <span
                      className={BOT_CATEGORY_BADGE[item.bot_category] ?? 'badge bg-secondary'}
                      style={{ minWidth: '180px' }}
                    >
                      {BOT_CATEGORY_LABELS[item.bot_category] ?? item.bot_category}
                    </span>
                    <div className="flex-grow-1 mx-3">
                      <div className="progress" style={{ height: '20px' }}>
                        <div
                          className={`progress-bar ${BOT_CATEGORY_PROGRESS[item.bot_category] ?? 'bg-secondary'}`}
                          style={{ width: `${pctOfBots(item.count)}%` }}
                        >
                          {pctOfBots(item.count)}%
                        </div>
                      </div>
                    </div>
                    <strong style={{ minWidth: '60px', textAlign: 'right' }}>{item.count}</strong>
                  </div>
                ))}
                {!stats.bot_categories?.length && <div className="text-center text-muted py-3">Немає даних</div>}
              </div>
            </div>
          </div>

          {/* Топ ботів */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Топ-10 ботів</strong></div>
              <div className="card-body">
                <table className="table table-sm table-hover mb-0">
                  <thead><tr><th>Бот</th><th className="text-end">Запитів</th></tr></thead>
                  <tbody>
                    {(stats.top_bots ?? []).map((item: any) => (
                      <tr key={item.bot_name}>
                        <td><i className="bi bi-robot" /> {item.bot_name}</td>
                        <td className="text-end"><strong>{item.count}</strong></td>
                      </tr>
                    ))}
                    {!stats.top_bots?.length && (
                      <tr><td colSpan={2} className="text-center text-muted py-3">Немає даних</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Динаміка */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Динаміка по днях</strong></div>
              <div className="card-body">
                {trend.labels.length > 0 ? (
                  <div style={{ maxHeight: '300px', overflowX: 'auto' }}>
                    <TrendChart labels={trend.labels} datasets={trend.datasets} />
                  </div>
                ) : (
                  <div className="text-center text-muted py-5">Немає даних</div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/pages/AnalyticsStats.vue
<template>
  <BaseLayout>
    <div class="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
      <div class="d-flex align-items-center gap-2">
        <router-link to="/analytics" class="btn btn-sm btn-outline-secondary">
          <i class="bi bi-arrow-left"></i> Назад
        </router-link>
        <h5 class="mb-0">Статистика відвідувань</h5>
      </div>
      <div class="d-flex gap-2">
        <select v-model="section" class="form-select form-select-sm" style="width:auto" @change="load">
          <option value="">Всі розділи</option>
          <option value="frontend">Frontend</option>
          <option value="admin">Адмінка</option>
        </select>
        <select v-model="days" class="form-select form-select-sm" style="width:auto" @change="load">
          <option :value="1">За 24 години</option>
          <option :value="7">За 7 днів</option>
          <option :value="14">За 14 днів</option>
          <option :value="30">За 30 днів</option>
          <option :value="60">За 60 днів</option>
          <option :value="90">За 90 днів</option>
        </select>
      </div>
    </div>

    <div v-if="loading" class="text-center py-5">
      <div class="spinner-border text-primary" role="status"></div>
    </div>
    <div v-else-if="error" class="alert alert-danger">{{ error }}</div>

    <div v-else-if="stats" class="row g-3">
      <!-- Summary Cards -->
      <div class="col-md-3">
        <div class="card text-center shadow-sm">
          <div class="card-body">
            <h6 class="text-muted mb-2">Всього переглядів</h6>
            <h2 class="mb-0">{{ stats.total }}</h2>
            <small class="text-muted">за {{ stats.period_days }} днів</small>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card text-center shadow-sm">
          <div class="card-body">
            <h6 class="text-muted mb-2">Унікальні відвідувачі</h6>
            <h2 class="mb-0">{{ stats.unique_visitors }}</h2>
            <small class="text-muted">по IP (без ботів)</small>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card text-center shadow-sm">
          <div class="card-body">
            <h6 class="text-muted mb-2">Середній час відповіді</h6>
            <h2 class="mb-0" :class="responseTimeClass(stats.response_time?.avg_time)">
              {{ Math.round(stats.response_time?.avg_time || 0) }}ms
            </h2>
            <small class="text-muted">макс: {{ stats.response_time?.max_time }}ms</small>
          </div>
        </div>
      </div>

      <div class="col-md-3">
        <div class="card text-center shadow-sm">
          <div class="card-body">
            <h6 class="text-muted mb-2">Боти</h6>
            <h2 class="mb-0">{{ botsCount }}</h2>
            <small class="text-muted">{{ botsPercent }}% трафіку</small>
          </div>
        </div>
      </div>

      <!-- Top Pages -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Топ-10 сторінок</strong>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover mb-0">
              <thead>
                <tr>
                  <th>URL</th>
                  <th class="text-end">Перегляди</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in stats.top_pages" :key="item.path">
                  <td><code class="small">{{ item.path }}</code></td>
                  <td class="text-end"><strong>{{ item.views }}</strong></td>
                </tr>
                <tr v-if="!stats.top_pages?.length">
                  <td colspan="2" class="text-center text-muted py-3">Немає даних</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Top Referers -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Топ-10 джерел</strong>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover mb-0">
              <thead>
                <tr>
                  <th>Referer</th>
                  <th class="text-end">К-сть</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in stats.top_referers" :key="item.referer">
                  <td class="small text-truncate" style="max-width: 300px">{{ shortUrl(item.referer) }}</td>
                  <td class="text-end"><strong>{{ item.count }}</strong></td>
                </tr>
                <tr v-if="!stats.top_referers?.length">
                  <td colspan="2" class="text-center text-muted py-3">Немає даних</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Device Types -->
      <div class="col-md-4">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>По пристроях</strong>
          </div>
          <div class="card-body">
            <div v-for="item in stats.by_device" :key="item.device_type" class="d-flex justify-content-between align-items-center mb-2">
              <span>
                <i :class="deviceIcon(item.device_type)"></i>
                {{ deviceName(item.device_type) }}
              </span>
              <strong>{{ item.count }}</strong>
            </div>
            <div v-if="!stats.by_device?.length" class="text-center text-muted py-3">Немає даних</div>
          </div>
        </div>
      </div>

      <!-- Browsers -->
      <div class="col-md-4">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>По браузерах</strong>
          </div>
          <div class="card-body">
            <div v-for="item in stats.by_browser" :key="item.browser" class="d-flex justify-content-between align-items-center mb-2">
              <span>{{ item.browser }}</span>
              <strong>{{ item.count }}</strong>
            </div>
            <div v-if="!stats.by_browser?.length" class="text-center text-muted py-3">Немає даних</div>
          </div>
        </div>
      </div>

      <!-- OS -->
      <div class="col-md-4">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>По ОС</strong>
          </div>
          <div class="card-body">
            <div v-for="item in stats.by_os" :key="item.os" class="d-flex justify-content-between align-items-center mb-2">
              <span>{{ item.os }}</span>
              <strong>{{ item.count }}</strong>
            </div>
            <div v-if="!stats.by_os?.length" class="text-center text-muted py-3">Немає даних</div>
          </div>
        </div>
      </div>

      <!-- Client Types Distribution -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>По типах клієнтів</strong>
          </div>
          <div class="card-body">
            <div v-for="item in stats.by_client_type" :key="item.client_type" class="d-flex justify-content-between align-items-center mb-2">
              <span :class="clientTypeBadge(item.client_type)" style="min-width: 140px">
                {{ clientTypeLabel(item.client_type) }}
              </span>
              <div class="flex-grow-1 mx-3">
                <div class="progress" style="height: 20px">
                  <div
                    class="progress-bar"
                    :class="clientTypeProgressColor(item.client_type)"
                    :style="`width: ${clientTypePercent(item.count)}%`"
                  >
                    {{ clientTypePercent(item.count) }}%
                  </div>
                </div>
              </div>
              <strong style="min-width: 60px; text-align: right">{{ item.count }}</strong>
            </div>
            <div v-if="!stats.by_client_type?.length" class="text-center text-muted py-3">Немає даних</div>
          </div>
        </div>
      </div>

      <!-- Bot Categories -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Категорії ботів</strong>
          </div>
          <div class="card-body">
            <div v-for="item in stats.bot_categories" :key="item.bot_category" class="d-flex justify-content-between align-items-center mb-2">
              <span :class="botCategoryBadge(item.bot_category)" style="min-width: 180px">
                {{ botCategoryLabel(item.bot_category) }}
              </span>
              <div class="flex-grow-1 mx-3">
                <div class="progress" style="height: 20px">
                  <div
                    class="progress-bar"
                    :class="botCategoryProgressColor(item.bot_category)"
                    :style="`width: ${botCategoryPercent(item.count)}%`"
                  >
                    {{ botCategoryPercent(item.count) }}%
                  </div>
                </div>
              </div>
              <strong style="min-width: 60px; text-align: right">{{ item.count }}</strong>
            </div>
            <div v-if="!stats.bot_categories?.length" class="text-center text-muted py-3">Немає даних</div>
          </div>
        </div>
      </div>

      <!-- Top Bots -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Топ-10 ботів</strong>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover mb-0">
              <thead>
                <tr>
                  <th>Бот</th>
                  <th class="text-end">Запитів</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in stats.top_bots" :key="item.bot_name">
                  <td><i class="bi bi-robot"></i> {{ item.bot_name }}</td>
                  <td class="text-end"><strong>{{ item.count }}</strong></td>
                </tr>
                <tr v-if="!stats.top_bots?.length">
                  <td colspan="2" class="text-center text-muted py-3">Немає даних</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Trend Chart -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Динаміка по днях</strong>
          </div>
          <div class="card-body">
            <div v-if="trendData.labels.length" style="max-height: 300px; overflow-x: auto;">
              <TrendChart :labels="trendData.labels" :datasets="trendData.datasets" :height="250" />
            </div>
            <div v-else class="text-center text-muted py-5">Немає даних</div>
          </div>
        </div>
      </div>
    </div>
  </BaseLayout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { authHeaders } from '@/utils/api'
import BaseLayout from '../layouts/BaseLayout.vue'
import TrendChart from '../components/TrendChart.vue'

const stats = ref(null)
const loading = ref(false)
const error = ref('')
const days = ref(7)
const section = ref('')

const botsCount = computed(() => {
  const botsData = stats.value?.bots_vs_real || []
  const bot = botsData.find(item => item.is_bot === 1)
  return bot?.count || 0
})

const botsPercent = computed(() => {
  if (!stats.value?.total) return 0
  return Math.round((botsCount.value / stats.value.total) * 100)
})

const trendData = computed(() => {
  if (!stats.value || !stats.value.trend) {
    return { labels: [], datasets: [] }
  }

  const dateMap = {}
  stats.value.trend.forEach(item => {
    if (!dateMap[item.date]) dateMap[item.date] = { real: 0, bots: 0 }
    if (item.is_bot === 0) dateMap[item.date].real = item.count
    else dateMap[item.date].bots = item.count
  })

  const labels = Object.keys(dateMap).sort()
  const datasets = [
    {
      label: 'Користувачі',
      data: labels.map(date => dateMap[date].real),
      color: 'var(--bs-primary)',
    },
    {
      label: 'Боти',
      data: labels.map(date => dateMap[date].bots),
      color: 'var(--bs-secondary-color)',
    },
  ]

  return { labels, datasets }
})


async function load() {
  loading.value = true
  error.value = ''

  const params = new URLSearchParams({ days: days.value })
  if (section.value) params.set('section', section.value)

  try {
    const res = await fetch(`/api/admin/analytics/stats?${params}`, { headers: authHeaders() })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = await res.json()
    if (json.status === 'success') {
      stats.value = json.data
    } else {
      error.value = json.message || 'Помилка завантаження'
    }
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

function responseTimeClass(time) {
  if (!time) return ''
  if (time < 100) return 'text-success'
  if (time < 500) return 'text-warning'
  return 'text-danger'
}

function deviceIcon(type) {
  const map = {
    mobile: 'bi-phone',
    tablet: 'bi-tablet',
    desktop: 'bi-display',
  }
  return map[type] || 'bi-question'
}

function deviceName(type) {
  const map = {
    mobile: 'Mobile',
    tablet: 'Tablet',
    desktop: 'Desktop',
  }
  return map[type] || type
}

function shortUrl(url) {
  if (!url) return '—'
  try {
    const u = new URL(url)
    return u.hostname
  } catch {
    return url.slice(0, 50)
  }
}

function clientTypeLabel(type) {
  const labels = {
    human: '👤 Люди',
    bot: '🤖 Боти',
    suspicious: '⚠️ Підозрілі',
    unknown: '❓ Невідомі',
  }
  return labels[type] || '⏳ Не класифіковано'
}

function clientTypeBadge(type) {
  const badges = {
    human: 'badge bg-success',
    bot: 'badge bg-secondary',
    suspicious: 'badge bg-warning text-dark',
    unknown: 'badge bg-info',
  }
  return badges[type] || 'badge bg-light text-dark'
}

function clientTypeProgressColor(type) {
  const colors = {
    human: 'bg-success',
    bot: 'bg-secondary',
    suspicious: 'bg-warning',
    unknown: 'bg-info',
  }
  return colors[type] || 'bg-light'
}

function clientTypePercent(count) {
  if (!stats.value?.total) return 0
  return Math.round((count / stats.value.total) * 100)
}

function botCategoryLabel(category) {
  const labels = {
    search_engine: '🔍 Пошукові системи',
    seo_tool: '📊 SEO інструменти',
    monitoring: '🔔 Моніторинг',
    scraper: '🤖 Scrapers',
    malicious: '🚫 Шкідливі',
  }
  return labels[category] || category
}

function botCategoryBadge(category) {
  const badges = {
    search_engine: 'badge bg-primary',
    seo_tool: 'badge bg-info',
    monitoring: 'badge bg-success',
    scraper: 'badge bg-warning text-dark',
    malicious: 'badge bg-danger',
  }
  return badges[category] || 'badge bg-secondary'
}

function botCategoryProgressColor(category) {
  const colors = {
    search_engine: 'bg-primary',
    seo_tool: 'bg-info',
    monitoring: 'bg-success',
    scraper: 'bg-warning',
    malicious: 'bg-danger',
  }
  return colors[category] || 'bg-secondary'
}

function botCategoryPercent(count) {
  if (!botsCount.value) return 0
  return Math.round((count / botsCount.value) * 100)
}

onMounted(() => load())
</script>
