// frontend-react/src/pages/ErrorLogStats.tsx
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import TrendChart from '@/components/charts/TrendChart'
import type { TrendDataset } from '@/components/charts/TrendChart'
import { apiGet } from '@/utils/api'
import { LEVEL_BADGE, LEVEL_COLOR, shortException } from './errorLogLevels'

interface Stats {
  total: number
  period_days: number
  by_level: Array<{ level: string; count: number }>
  by_category: Array<{ category: string; count: number }>
  by_exception: Array<{ exception_class: string; count: number }>
  trend: Array<{ date: string; level: string; count: number }>
}

function buildTrend(stats: Stats | null): { labels: string[]; datasets: TrendDataset[] } {
  if (!stats?.trend) return { labels: [], datasets: [] }

  const dateMap: Record<string, Record<string, number>> = {}
  for (const item of stats.trend) {
    dateMap[item.date] ??= {}
    dateMap[item.date][item.level] = item.count
  }

  const labels = Object.keys(dateMap).sort()
  const datasets: TrendDataset[] = []

  for (const level of ['error', 'critical', 'warning', 'alert', 'emergency']) {
    const data = labels.map(date => dateMap[date][level] || 0)
    if (data.reduce((s, v) => s + v, 0) > 0) {
      datasets.push({ label: level, data, color: LEVEL_COLOR[level] ?? '#6c757d' })
    }
  }

  return { labels, datasets }
}

export default function ErrorLogStats() {
  const [stats, setStats] = useState<Stats | null>(null)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [days, setDays] = useState(7)

  const load = useCallback(async () => {
    setLoading(true)
    setError('')
    try {
      const res = await apiGet(`/admin/error-logs/stats?days=${days}`)
      setStats(res.data)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Помилка завантаження')
    } finally {
      setLoading(false)
    }
  }, [days])

  useEffect(() => { load() }, [load])

  const trend = buildTrend(stats)

  return (
    <div>
      <div className="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
        <div className="d-flex align-items-center gap-2">
          <Link to="/error-logs" className="btn btn-sm btn-outline-secondary">
            <i className="bi bi-arrow-left" /> Назад
          </Link>
          <h5 className="mb-0">Статистика помилок</h5>
        </div>
        <div className="d-flex gap-2">
          <select
            value={days}
            onChange={(e) => setDays(Number(e.target.value))}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            {[7, 14, 30, 60, 90].map(d => (
              <option key={d} value={d}>За {d} днів</option>
            ))}
          </select>
        </div>
      </div>

      {loading && (
        <div className="text-center py-5">
          <div className="spinner-border text-primary" />
        </div>
      )}

      {!loading && error && <div className="alert alert-danger">{error}</div>}

      {!loading && !error && stats && (
        <div className="row g-3">
          {/* Всього */}
          <div className="col-md-3">
            <div className="card text-center shadow-sm">
              <div className="card-body">
                <h6 className="text-muted mb-2">Всього помилок</h6>
                <h2 className="mb-0">{stats.total}</h2>
                <small className="text-muted">за {stats.period_days} днів</small>
              </div>
            </div>
          </div>

          {/* По рівнях */}
          <div className="col-md-9">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>По рівнях</strong></div>
              <div className="card-body">
                <div className="row g-2">
                  {stats.by_level.map(item => (
                    <div key={item.level} className="col-md-4">
                      <div className="d-flex justify-content-between align-items-center p-2 border rounded">
                        <span className={LEVEL_BADGE[item.level] ?? 'badge bg-secondary'}>{item.level}</span>
                        <strong>{item.count}</strong>
                      </div>
                    </div>
                  ))}
                  {stats.by_level.length === 0 && (
                    <div className="col-12 text-center text-muted py-3">Немає даних</div>
                  )}
                </div>
              </div>
            </div>
          </div>

          {/* Топ категорій */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Топ-10 категорій</strong></div>
              <div className="card-body">
                <table className="table table-sm table-hover mb-0">
                  <thead>
                    <tr>
                      <th>Категорія</th>
                      <th className="text-end">Кількість</th>
                    </tr>
                  </thead>
                  <tbody>
                    {stats.by_category.map(item => (
                      <tr key={item.category}>
                        <td><code className="small">{item.category}</code></td>
                        <td className="text-end"><strong>{item.count}</strong></td>
                      </tr>
                    ))}
                    {stats.by_category.length === 0 && (
                      <tr><td colSpan={2} className="text-center text-muted py-3">Немає даних</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Топ exceptions */}
          <div className="col-md-6">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Топ-10 exceptions</strong></div>
              <div className="card-body">
                <table className="table table-sm table-hover mb-0">
                  <thead>
                    <tr>
                      <th>Exception</th>
                      <th className="text-end">Кількість</th>
                    </tr>
                  </thead>
                  <tbody>
                    {stats.by_exception.map(item => (
                      <tr key={item.exception_class}>
                        <td>
                          <code className="small" title={item.exception_class}>
                            {shortException(item.exception_class)}
                          </code>
                        </td>
                        <td className="text-end"><strong>{item.count}</strong></td>
                      </tr>
                    ))}
                    {stats.by_exception.length === 0 && (
                      <tr><td colSpan={2} className="text-center text-muted py-3">Немає даних</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            </div>
          </div>

          {/* Динаміка */}
          <div className="col-12">
            <div className="card shadow-sm">
              <div className="card-header bg-light"><strong>Динаміка помилок по днях</strong></div>
              <div className="card-body">
                {trend.labels.length > 0 ? (
                  <div style={{ maxHeight: '400px', overflowX: 'auto' }}>
                    <TrendChart labels={trend.labels} datasets={trend.datasets} />
                  </div>
                ) : (
                  <div className="text-center text-muted py-5">Немає даних для графіка</div>
                )}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}

// frontend/src/pages/ErrorLogStats.vue
<template>
  <BaseLayout>
    <div class="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
      <div class="d-flex align-items-center gap-2">
        <router-link to="/error-logs" class="btn btn-sm btn-outline-secondary">
          <i class="bi bi-arrow-left"></i> Назад
        </router-link>
        <h5 class="mb-0">Статистика помилок</h5>
      </div>
      <div class="d-flex gap-2">
        <select v-model="days" class="form-select form-select-sm" style="width:auto" @change="load">
          <option :value="7">За 7 днів</option>
          <option :value="14">За 14 днів</option>
          <option :value="30">За 30 днів</option>
          <option :value="60">За 60 днів</option>
          <option :value="90">За 90 днів</option>
        </select>
      </div>
    </div>

    <div v-if="loading" class="text-center py-5">
      <div class="spinner-border text-primary" role="status"></div>
    </div>
    <div v-else-if="error" class="alert alert-danger">{{ error }}</div>

    <div v-else-if="stats" class="row g-3">
      <!-- Total -->
      <div class="col-md-3">
        <div class="card text-center shadow-sm">
          <div class="card-body">
            <h6 class="text-muted mb-2">Всього помилок</h6>
            <h2 class="mb-0">{{ stats.total }}</h2>
            <small class="text-muted">за {{ stats.period_days }} днів</small>
          </div>
        </div>
      </div>

      <!-- By Level -->
      <div class="col-md-9">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>По рівнях</strong>
          </div>
          <div class="card-body">
            <div class="row g-2">
              <div v-for="item in stats.by_level" :key="item.level" class="col-md-4">
                <div class="d-flex justify-content-between align-items-center p-2 border rounded">
                  <span :class="levelBadge(item.level)">{{ item.level }}</span>
                  <strong>{{ item.count }}</strong>
                </div>
              </div>
              <div v-if="!stats.by_level.length" class="col-12 text-center text-muted py-3">
                Немає даних
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- By Category -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Топ-10 категорій</strong>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover mb-0">
              <thead>
                <tr>
                  <th>Категорія</th>
                  <th class="text-end">Кількість</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in stats.by_category" :key="item.category">
                  <td><code class="small">{{ item.category }}</code></td>
                  <td class="text-end"><strong>{{ item.count }}</strong></td>
                </tr>
                <tr v-if="!stats.by_category.length">
                  <td colspan="2" class="text-center text-muted py-3">Немає даних</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- By Exception -->
      <div class="col-md-6">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Топ-10 exceptions</strong>
          </div>
          <div class="card-body">
            <table class="table table-sm table-hover mb-0">
              <thead>
                <tr>
                  <th>Exception</th>
                  <th class="text-end">Кількість</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in stats.by_exception" :key="item.exception_class">
                  <td>
                    <code class="small" :title="item.exception_class">{{ shortException(item.exception_class) }}</code>
                  </td>
                  <td class="text-end"><strong>{{ item.count }}</strong></td>
                </tr>
                <tr v-if="!stats.by_exception.length">
                  <td colspan="2" class="text-center text-muted py-3">Немає даних</td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>
      </div>

      <!-- Trend Chart -->
      <div class="col-12">
        <div class="card shadow-sm">
          <div class="card-header bg-light">
            <strong>Динаміка помилок по днях</strong>
          </div>
          <div class="card-body">
            <div v-if="trendData.labels.length" style="max-height: 400px; overflow-x: auto;">
              <TrendChart :labels="trendData.labels" :datasets="trendData.datasets" />
            </div>
            <div v-else class="text-center text-muted py-5">
              Немає даних для графіка
            </div>
          </div>
        </div>
      </div>
    </div>
  </BaseLayout>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { authHeaders } from '@/utils/api'
import BaseLayout from '../layouts/BaseLayout.vue'
import TrendChart from '../components/TrendChart.vue'

const stats = ref(null)
const loading = ref(false)
const error = ref('')
const days = ref(7)


async function load() {
  loading.value = true
  error.value = ''

  try {
    const res = await fetch(`/api/admin/error-logs/stats?days=${days.value}`, { headers: authHeaders() })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = await res.json()
    if (json.status === 'success') {
      stats.value = json.data
    } else {
      error.value = json.message || 'Помилка завантаження'
    }
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

const trendData = computed(() => {
  if (!stats.value || !stats.value.trend) {
    return { labels: [], datasets: [] }
  }

  // Group by date
  const dateMap = {}
  stats.value.trend.forEach(item => {
    if (!dateMap[item.date]) dateMap[item.date] = {}
    dateMap[item.date][item.level] = item.count
  })

  const labels = Object.keys(dateMap).sort()
  const levels = ['error', 'critical', 'warning', 'alert', 'emergency']
  const datasets = []

  levels.forEach(level => {
    const data = labels.map(date => dateMap[date][level] || 0)
    const total = data.reduce((sum, val) => sum + val, 0)
    if (total > 0) {
      datasets.push({
        label: level,
        data,
        color: levelColor(level),
      })
    }
  })

  return { labels, datasets }
})

function levelBadge(level) {
  const map = {
    error: 'badge bg-danger',
    critical: 'badge bg-danger',
    alert: 'badge bg-warning text-dark',
    emergency: 'badge bg-dark',
    warning: 'badge bg-warning text-dark',
  }
  return map[level] || 'badge bg-secondary'
}

function levelColor(level) {
  const map = {
    error: 'var(--bs-danger)',
    critical: 'var(--bs-danger-dark)',
    alert: 'var(--bs-warning)',
    emergency: 'var(--bs-dark)',
    warning: 'var(--bs-orange)',
  }
  return map[level] || 'var(--bs-secondary-color)'
}

function shortException(str) {
  if (!str) return '—'
  const parts = str.split('\\')
  return parts[parts.length - 1]
}

onMounted(() => load())
</script>
