// frontend-react/src/pages/PermissionList.tsx
import { useEffect, useRef, useState } from 'react'
import { apiGet, apiPut } from '@/utils/api'
import { notify } from '@/hooks/useNotify'

interface Permission {
  id: number
  slug: string
  name: string
  module: string | null
  description: string | null
  is_system: boolean
}

export default function PermissionList() {
  const [permissions, setPermissions] = useState<Permission[]>([])
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const [editingId, setEditingId] = useState<number | null>(null)
  const [editingDescription, setEditingDescription] = useState('')
  const [saving, setSaving] = useState(false)
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  useEffect(() => {
    apiGet('/admin/permissions')
      .then(res => setPermissions(res.permissions ?? []))
      .catch(err => setError(err instanceof Error ? err.message : "Помилка з'єднання з сервером"))
      .finally(() => setLoading(false))
  }, [])

  useEffect(() => {
    if (editingId !== null) textareaRef.current?.focus()
  }, [editingId])

  const startEdit = (perm: Permission) => {
    setEditingId(perm.id)
    setEditingDescription(perm.description ?? '')
  }

  const cancelEdit = () => {
    setEditingId(null)
    setEditingDescription('')
  }

  const saveDescription = async (perm: Permission) => {
    setSaving(true)
    try {
      await apiPut(`/admin/permissions/${perm.id}`, { description: editingDescription })
      setPermissions(list =>
        list.map(p => (p.id === perm.id ? { ...p, description: editingDescription } : p))
      )
      cancelEdit()
    } catch (err) {
      notify(err instanceof Error ? err.message : 'Помилка збереження', { type: 'error' })
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="container-fluid py-4">
      <div className="d-flex justify-content-between align-items-center mb-4">
        <h4 className="mb-0">Права доступу (Permissions)</h4>
      </div>

      {loading && (
        <div className="text-center py-5">
          <div className="spinner-border text-primary" />
        </div>
      )}

      {!loading && error && <div className="alert alert-danger">{error}</div>}

      {!loading && !error && (
        <>
          <div className="card">
            <div className="card-body p-0">
              <table className="table table-hover mb-0">
                <thead className="table-light">
                  <tr>
                    <th style={{ width: '60px' }}>ID</th>
                    <th style={{ width: '200px' }}>Slug</th>
                    <th style={{ width: '250px' }}>Назва</th>
                    <th style={{ width: '120px' }}>Модуль</th>
                    <th>Опис</th>
                    <th style={{ width: '80px' }} className="text-center">Системний</th>
                  </tr>
                </thead>
                <tbody>
                  {permissions.map(perm => (
                    <tr key={perm.id}>
                      <td className="text-muted">{perm.id}</td>
                      <td><code className="small">{perm.slug}</code></td>
                      <td>{perm.name}</td>
                      <td>
                        {perm.module
                          ? <span className="badge bg-secondary">{perm.module}</span>
                          : <span className="text-muted small">—</span>}
                      </td>
                      <td>
                        {editingId === perm.id ? (
                          <div className="d-flex gap-2">
                            <textarea
                              ref={textareaRef}
                              value={editingDescription}
                              onChange={(e) => setEditingDescription(e.target.value)}
                              onKeyUp={(e) => { if (e.key === 'Escape') cancelEdit() }}
                              className="form-control form-control-sm"
                              rows={3}
                            />
                            <div className="d-flex flex-column gap-1">
                              <button
                                className="btn btn-sm btn-success"
                                disabled={saving}
                                title="Зберегти"
                                onClick={() => saveDescription(perm)}
                              >
                                <i className="bi bi-check-lg" />
                              </button>
                              <button className="btn btn-sm btn-secondary" title="Скасувати" onClick={cancelEdit}>
                                <i className="bi bi-x-lg" />
                              </button>
                            </div>
                          </div>
                        ) : (
                          <div
                            className="text-muted small"
                            style={{ cursor: 'pointer', whiteSpace: 'pre-wrap' }}
                            title="Подвійний клік для редагування"
                            onDoubleClick={() => startEdit(perm)}
                          >
                            {perm.description || '—'}
                          </div>
                        )}
                      </td>
                      <td className="text-center">
                        {perm.is_system
                          ? <span className="text-success" title="Системний запис"><i className="bi bi-shield-lock-fill" /></span>
                          : <span className="text-muted">—</span>}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>

          <div className="mt-3 text-muted small">
            <i className="bi bi-info-circle me-1" />
            Всього записів: {permissions.length}. Подвійний клік по опису для редагування.
          </div>
        </>
      )}
    </div>
  )
}

// frontend/src/pages/PermissionList.vue
<template>
  <BaseLayout>
    <div class="container-fluid py-4">
      <div class="d-flex justify-content-between align-items-center mb-4">
        <h4 class="mb-0">Права доступу (Permissions)</h4>
      </div>

      <div v-if="loading" class="text-center py-5">
        <div class="spinner-border text-primary" role="status"></div>
      </div>

      <div v-else-if="error" class="alert alert-danger">{{ error }}</div>

      <div v-else class="card">
        <div class="card-body p-0">
          <table class="table table-hover mb-0">
            <thead class="table-light">
              <tr>
                <th style="width: 60px">ID</th>
                <th style="width: 200px">Slug</th>
                <th style="width: 250px">Назва</th>
                <th style="width: 120px">Модуль</th>
                <th>Опис</th>
                <th style="width: 80px" class="text-center">Системний</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="perm in permissions" :key="perm.id">
                <td class="text-muted">{{ perm.id }}</td>
                <td><code class="small">{{ perm.slug }}</code></td>
                <td>{{ perm.name }}</td>
                <td>
                  <span v-if="perm.module" class="badge bg-secondary">{{ perm.module }}</span>
                  <span v-else class="text-muted small">—</span>
                </td>
                <td>
                  <div v-if="editingId === perm.id" class="d-flex gap-2">
                    <textarea
                      v-model="editingDescription"
                      class="form-control form-control-sm"
                      rows="3"
                      @keyup.esc="cancelEdit"
                      ref="descriptionInput"
                    ></textarea>
                    <div class="d-flex flex-column gap-1">
                      <button
                        @click="saveDescription(perm)"
                        class="btn btn-sm btn-success"
                        :disabled="saving"
                        title="Зберегти"
                      >
                        <i class="bi bi-check-lg"></i>
                      </button>
                      <button
                        @click="cancelEdit"
                        class="btn btn-sm btn-secondary"
                        title="Скасувати"
                      >
                        <i class="bi bi-x-lg"></i>
                      </button>
                    </div>
                  </div>
                  <div
                    v-else
                    class="text-muted small"
                    @dblclick="startEdit(perm)"
                    style="cursor: pointer; white-space: pre-wrap;"
                    :title="'Подвійний клік для редагування'"
                  >
                    {{ perm.description || '—' }}
                  </div>
                </td>
                <td class="text-center">
                  <span v-if="perm.is_system" class="text-success" title="Системний запис">
                    <i class="bi bi-shield-lock-fill"></i>
                  </span>
                  <span v-else class="text-muted">—</span>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div v-if="!loading && !error" class="mt-3 text-muted small">
        <i class="bi bi-info-circle me-1"></i>
        Всього записів: {{ permissions.length }}. Подвійний клік по опису для редагування.
      </div>
    </div>
  </BaseLayout>
</template>

<script setup>
import { ref, onMounted, nextTick } from 'vue';
import { useAuth } from '@/composables/useAuth';
import { useNotify } from '@/composables/useNotify';
import BaseLayout from '@/layouts/BaseLayout.vue';

const auth = useAuth();
const { notify } = useNotify();

const permissions = ref([]);
const loading = ref(true);
const error = ref(null);
const editingId = ref(null);
const editingDescription = ref('');
const saving = ref(false);
const descriptionInput = ref(null);

onMounted(async () => {
  await loadPermissions();
});

async function loadPermissions() {
  loading.value = true;
  error.value = null;

  try {
    const response = await fetch('/api/admin/permissions', {
      headers: auth.authHeaders(),
    });
    const json = await response.json();

    if (json.status === 'success') {
      permissions.value = json.permissions;
    } else {
      error.value = json.message || 'Помилка завантаження прав доступу';
    }
  } catch (e) {
    error.value = "Помилка з'єднання з сервером";
  } finally {
    loading.value = false;
  }
}

async function startEdit(perm) {
  editingId.value = perm.id;
  editingDescription.value = perm.description || '';
  await nextTick();
  if (descriptionInput.value) {
    descriptionInput.value.focus();
  }
}

function cancelEdit() {
  editingId.value = null;
  editingDescription.value = '';
}

async function saveDescription(perm) {
  saving.value = true;

  try {
    const response = await fetch(`/api/admin/permissions/${perm.id}`, {
      method: 'PUT',
      headers: {
        'Content-Type': 'application/json',
        ...auth.authHeaders(),
      },
      body: JSON.stringify({ description: editingDescription.value }),
    });
    const json = await response.json();

    if (json.status === 'success') {
      perm.description = editingDescription.value;
      cancelEdit();
    } else {
      notify(json.message || 'Помилка збереження', { type: 'error' });
    }
  } catch (e) {
    notify("Помилка з'єднання з сервером", { type: 'error' });
  } finally {
    saving.value = false;
  }
}
</script>

<style scoped>
tbody tr:hover {
  background-color: rgba(0, 0, 0, 0.02);
}
</style>
