// frontend/src/pages/Analytics.vue
<template>
  <AnalyticsDetailsModal />
  <ChangeClientTypeModal />
  <ListPageWrapper>
    <div>
    <div class="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
      <div class="d-flex align-items-center gap-2">
        <h5 class="mb-0">Аналітика відвідувань</h5>
        <router-link to="/analytics/stats" class="btn btn-sm btn-outline-primary">
          <i class="bi bi-bar-chart"></i> Статистика
        </router-link>
        <router-link to="/analytics/charts" class="btn btn-sm btn-outline-primary">
          <i class="bi bi-graph-up-arrow"></i> Графіки
        </router-link>
      </div>
      <div class="d-flex gap-2 flex-wrap">
        <input
          v-model="search"
          type="text"
          class="form-control form-control-sm"
          style="width:200px"
          placeholder="Пошук..."
          @input="debounceLoad"
        />
        <select v-model="clientTypeFilter" class="form-select form-select-sm" style="width:220px" @change="load(1)">
          <option value="">Всі типи клієнтів</option>

          <optgroup label="👤 Люди">
            <option value="human">Всі люди</option>
            <option value="human_desktop">🖥️ Desktop</option>
            <option value="human_mobile">📱 Mobile</option>
            <option value="human_tablet">📲 Tablet</option>
            <option value="human_unknown">❓ Невідомі</option>
          </optgroup>

          <optgroup label="🔍 Пошукові системи">
            <option value="bot_search_engine">Всі пошукові системи</option>
            <option value="bot_search_google">Google</option>
            <option value="bot_search_yandex">Yandex</option>
            <option value="bot_search_bing">Bing</option>
            <option value="bot_search_other">Інші</option>
            <option value="bot_search_unknown">❓ Невідомі</option>
          </optgroup>

          <optgroup label="📊 SEO інструменти">
            <option value="bot_seo_tool">Всі SEO інструменти</option>
            <option value="bot_seo_unknown">❓ Невідомі</option>
          </optgroup>

          <optgroup label="🔔 Моніторинг">
            <option value="bot_monitoring">Всі моніторинг-сервіси</option>
            <option value="bot_monitoring_unknown">❓ Невідомі</option>
          </optgroup>

          <optgroup label="🚫 Погані боти">
            <option value="bot_scraper">🤖 Scrapers</option>
            <option value="bot_malicious">⚠️ Malicious (сканери)</option>
            <option value="bot_bad_unknown">❓ Невідомі</option>
          </optgroup>

          <optgroup label="Інше">
            <option value="suspicious">⚠️ Підозрілі</option>
            <option value="unknown">❓ Невідомі</option>
            <option value="unclassified">⏳ Не проаналізовані</option>
          </optgroup>
        </select>
        <select v-model="deviceFilter" class="form-select form-select-sm" style="width:auto" @change="load(1)">
          <option value="">Всі пристрої</option>
          <option value="desktop">Desktop</option>
          <option value="mobile">Mobile</option>
          <option value="tablet">Tablet</option>
        </select>
        <select v-model="statusFilter" class="form-select form-select-sm" style="width:auto" @change="load(1)">
          <option value="">Всі статуси</option>
          <option value="200">200 OK</option>
          <option value="201">201 Created</option>
          <option value="204">204 No Content</option>
          <option value="301">301 Moved</option>
          <option value="302">302 Found</option>
          <option value="400">400 Bad Request</option>
          <option value="401">401 Unauthorized</option>
          <option value="403">403 Forbidden</option>
          <option value="404">404 Not Found</option>
          <option value="422">422 Unprocessable</option>
          <option value="500">500 Server Error</option>
          <option value="503">503 Unavailable</option>
          <option value="other">Інші статуси</option>
        </select>
        <select v-model="methodFilter" class="form-select form-select-sm" style="width:auto" @change="load(1)">
          <option value="">Всі методи</option>
          <option value="GET">GET</option>
          <option value="POST">POST</option>
          <option value="PUT">PUT</option>
          <option value="PATCH">PATCH</option>
          <option value="DELETE">DELETE</option>
          <option value="other">Інші методи</option>
        </select>
        <input
          v-model="filterDateFrom"
          type="date"
          class="form-control form-control-sm"
          style="width:auto"
          @change="load(1)"
        />
        <input
          v-model="filterDateTo"
          type="date"
          class="form-control form-control-sm"
          style="width:auto"
          @change="load(1)"
        />
        <div class="input-group" style="width:auto">
          <input
            v-model="ipFilter"
            type="text"
            class="form-control form-control-sm"
            style="width:150px"
            placeholder="IP адреса..."
            @input="debounceLoad"
          />
          <button
            class="btn btn-sm btn-outline-secondary"
            type="button"
            title="Показати мій IP"
            @click="showMyIp"
          >
            <i class="bi bi-hdd-network"></i>
          </button>
        </div>
      </div>
    </div>

    <!-- Bulk actions panel -->
    <div v-if="selected.length > 0" class="alert alert-info d-flex align-items-center gap-2 mb-3">
      <span><strong>{{ selected.length }}</strong> обрано</span>
      <select v-model="bulkClientType" class="form-select form-select-sm" style="width:auto">
        <option value="">Змінити тип на...</option>
        <option value="human">👤 Людина</option>
        <option value="bot">🤖 Бот</option>
        <option value="suspicious">⚠️ Підозрілий</option>
        <option value="unknown">❓ Невідомий</option>
      </select>
      <button
        class="btn btn-sm btn-primary"
        :disabled="!bulkClientType"
        @click="applyBulkChange"
      >
        Застосувати
      </button>
      <button class="btn btn-sm btn-outline-secondary" @click="clearSelection">Скасувати</button>
    </div>

    <div v-if="loading" class="text-center py-5">
      <div class="spinner-border text-primary" role="status"></div>
    </div>
    <div v-else-if="error" class="alert alert-danger">{{ error }}</div>

    <div v-else>
      <div class="card shadow-sm">
        <div class="table-responsive">
          <table class="table table-hover align-middle mb-0 small">
            <thead class="table-light">
              <tr>
                <th style="width:40px">
                  <input
                    type="checkbox"
                    class="form-check-input"
                    :checked="isAllSelected"
                    @change="toggleSelectAll"
                    title="Вибрати всі"
                  />
                </th>
                <th style="width:60px" class="text-end th-sortable" @click="toggleSort('id')">
                  ID <SortIcon col="id" :sortKey :sortDir />
                </th>
                <th class="th-sortable" @click="toggleSort('path')">
                  URL <SortIcon col="path" :sortKey :sortDir />
                </th>
                <th style="width:60px" class="th-sortable" @click="toggleSort('method')">
                  Method <SortIcon col="method" :sortKey :sortDir />
                </th>
                <th style="width:70px" class="th-sortable" @click="toggleSort('status_code')">
                  Status <SortIcon col="status_code" :sortKey :sortDir />
                </th>
                <th style="width:130px" class="th-sortable" @click="toggleSort('ip')">
                  IP <SortIcon col="ip" :sortKey :sortDir />
                </th>
                <th class="th-sortable" @click="toggleSort('referer')">
                  Referer <SortIcon col="referer" :sortKey :sortDir />
                </th>
                <th style="width:140px" class="th-sortable" @click="toggleSort('client_type')">
                  Тип / Device <SortIcon col="client_type" :sortKey :sortDir />
                </th>
                <th class="th-sortable" @click="toggleSort('browser')">
                  Browser <SortIcon col="browser" :sortKey :sortDir />
                </th>
                <th class="th-sortable" @click="toggleSort('user_id')">
                  User <SortIcon col="user_id" :sortKey :sortDir />
                </th>
                <th style="width:90px" class="th-sortable text-end" @click="toggleSort('response_time')">
                  Time <SortIcon col="response_time" :sortKey :sortDir />
                </th>
                <th style="width:140px" class="th-sortable" @click="toggleSort('created_at')">
                  Дата <SortIcon col="created_at" :sortKey :sortDir />
                </th>
                <th style="width:80px"></th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="row in items" :key="row.id" :class="rowClass(row)">
                <td>
                  <input
                    type="checkbox"
                    class="form-check-input"
                    :checked="selected.includes(row.id)"
                    @change="toggleSelect(row.id)"
                  />
                </td>
                <td class="text-muted text-end">{{ row.id }}</td>
                <td>
                  <div class="text-truncate" style="max-width: 300px" :title="row.path">
                    {{ row.path }}
                  </div>
                </td>
                <td><span :class="methodBadge(row.method)">{{ row.method }}</span></td>
                <td><span :class="statusBadge(row.status_code)">{{ row.status_code }}</span></td>
                <td class="small">
                  <a
                    href="#"
                    class="text-decoration-none"
                    :title="`Фільтрувати за IP: ${row.ip}`"
                    @click.prevent="filterByIp(row.ip)"
                  >
                    <i class="bi bi-filter-circle"></i> {{ row.ip }}
                  </a>
                </td>
                <td class="text-muted small">
                  <div class="text-truncate" style="max-width: 200px" :title="row.referer">
                    {{ shortReferer(row.referer) }}
                  </div>
                </td>
                <td>
                  <span
                    :class="clientTypeBadge(row.client_type)"
                    style="cursor: pointer"
                    :title="`Клік щоб змінити тип. Метод: ${row.detection_method || 'не вказано'}`"
                    @click="changeClientType(row.id, row.client_type)"
                  >
                    {{ smartClientLabel(row) }}
                  </span>
                </td>
                <td class="text-muted small">
                  {{ row.browser || '—' }}
                </td>
                <td class="text-muted small">
                  <span v-if="row.user_id" :title="row.email">#{{ row.user_id }} {{ row.username }}</span>
                  <span v-else>—</span>
                </td>
                <td class="text-end">
                  <span :class="responseTimeClass(row.response_time)">{{ row.response_time }}ms</span>
                </td>
                <td class="text-muted" style="white-space:nowrap">
                  {{ formatDate(row.created_at) }}
                </td>
                <td class="text-center">
                  <button
                    class="btn btn-sm btn-outline-primary"
                    @click="showDetails(row.id)"
                    title="Детальна інформація"
                  >
                    <i class="bi bi-info-circle"></i>
                  </button>
                </td>
              </tr>
              <tr v-if="!items.length">
                <td colspan="14" class="text-center text-muted py-4">Немає даних</td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>

      <div class="d-flex justify-content-between align-items-center mt-3">
        <span class="text-muted small">Всього: {{ total }}</span>
        <Pagination :current-page="page" :total-pages="totalPages" @change="load" />
      </div>
    </div>
    </div>
    </ListPageWrapper>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { authHeaders } from '@/utils/api'
import { useNotify } from '../composables/useNotify'
import { useUrlFilters } from '../composables/useUrlFilters'
import { formatDate } from '../utils/date'
import ListPageWrapper from '../components/ListPageWrapper.vue'
import SortIcon from '../components/SortIcon.vue'
import Pagination from '../components/Pagination.vue'
import AnalyticsDetailsModal from '../components/AnalyticsDetailsModal.vue'
import ChangeClientTypeModal from '../components/ChangeClientTypeModal.vue'

const { notify } = useNotify()

// Page layout для управления отступами при docked модальных окнах
const items = ref([])
const loading = ref(false)
const error = ref('')
const page = ref(1)
const perPage = ref(100)
const total = ref(0)
const search = ref('')
const sectionFilter = ref('')
const clientTypeFilter = ref('human') // По умолчанию показываем людей
const deviceFilter = ref('')
const statusFilter = ref('')
const methodFilter = ref('')
const filterDateFrom = ref('')
const filterDateTo = ref('')
const ipFilter = ref('')
const sortKey = ref('created_at')
const sortDir = ref('DESC')
const selected = ref([])
const bulkClientType = ref('')
const detailId = ref(null)

// Настройка синхронизации с URL
const { initFromUrl } = useUrlFilters({
  filters: {
    search,
    section: sectionFilter,
    client_type: clientTypeFilter,
    device_type: deviceFilter,
    status_code: statusFilter,
    method: methodFilter,
    date_from: filterDateFrom,
    date_to: filterDateTo,
    ip: ipFilter,
    page
  },
  sorting: {
    sortKey,
    sortDir
  },
  detail: {
    id: detailId,
    onOpen: (id) => {
      window.dispatchEvent(new CustomEvent('show-analytics-details', { detail: { id } }))
    }
  }
})

const totalPages = computed(() => Math.ceil(total.value / perPage.value))
const isAllSelected = computed(() => {
  return items.value.length > 0 && items.value.every(row => selected.value.includes(row.id))
})


async function load(p = 1) {
  loading.value = true
  error.value = ''
  page.value = p

  const params = new URLSearchParams({
    page: page.value,
    per_page: perPage.value,
    sort_by: sortKey.value,
    sort_dir: sortDir.value,
  })
  if (search.value) params.set('search', search.value)
  if (sectionFilter.value) params.set('section', sectionFilter.value)
  if (clientTypeFilter.value) params.set('client_type', clientTypeFilter.value)
  if (deviceFilter.value) params.set('device_type', deviceFilter.value)
  if (statusFilter.value) params.set('status_code', statusFilter.value)
  if (methodFilter.value) params.set('method', methodFilter.value)
  if (filterDateFrom.value) params.set('date_from', filterDateFrom.value)
  if (filterDateTo.value) params.set('date_to', filterDateTo.value)
  if (ipFilter.value) params.set('ip', ipFilter.value)

  try {
    const res = await fetch(`/api/admin/analytics/pageviews?${params}`, { headers: authHeaders() })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = await res.json()
    if (json.status === 'success') {
      items.value = json.data
      total.value = json.pagination.total
    } else {
      error.value = json.message || 'Помилка завантаження'
    }
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

function toggleSort(col) {
  if (sortKey.value === col) {
    sortDir.value = sortDir.value === 'ASC' ? 'DESC' : 'ASC'
  } else {
    sortKey.value = col
    sortDir.value = 'DESC'
  }
  load(1)
}

let debounceTimer
function debounceLoad() {
  clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => load(1), 400)
}

function rowClass(row) {
  if (row.status_code >= 500) return 'table-danger'
  if (row.status_code >= 400) return 'table-warning'
  return ''
}

function methodBadge(method) {
  const map = {
    GET: 'badge bg-primary',
    POST: 'badge bg-success',
    PUT: 'badge bg-warning text-dark',
    DELETE: 'badge bg-danger',
  }
  return map[method] || 'badge bg-secondary'
}

function statusBadge(code) {
  if (code >= 200 && code < 300) return 'badge bg-success'
  if (code >= 300 && code < 400) return 'badge bg-info'
  if (code >= 400 && code < 500) return 'badge bg-warning text-dark'
  if (code >= 500) return 'badge bg-danger'
  return 'badge bg-secondary'
}

function deviceIcon(type) {
  const map = {
    mobile: 'bi-phone',
    tablet: 'bi-tablet',
    desktop: 'bi-display',
  }
  return map[type] || 'bi-question'
}

function responseTimeClass(time) {
  if (!time) return 'text-muted'
  if (time < 100) return 'text-success'
  if (time < 500) return 'text-warning'
  return 'text-danger'
}

function shortReferer(ref) {
  if (!ref) return '—'
  try {
    const url = new URL(ref)
    return url.hostname
  } catch {
    return ref.slice(0, 30)
  }
}


function filterByIp(ip) {
  ipFilter.value = ip
  load(1)
}

function showDetails(id) {
  detailId.value = id
  window.dispatchEvent(new CustomEvent('show-analytics-details', { detail: { id } }))
}

function clientTypeLabel(type) {
  const labels = {
    human: '👤 Людина',
    bot: '🤖 Бот',
    suspicious: '⚠️ Підозрілий',
    unknown: '❓ Невідомий',
  }
  return labels[type] || '⏳ Не класифіковано'
}

// Smart label: combines client type + device/bot name
function smartClientLabel(row) {
  // Humans - show device
  if (row.client_type === 'human') {
    if (row.device_type === 'desktop') return '👤 🖥️ Desktop'
    if (row.device_type === 'mobile') return '👤 📱 Mobile'
    if (row.device_type === 'tablet') return '👤 📲 Tablet'
    return '👤 Людина'
  }

  // Bots - show search engine name or category
  if (row.client_type === 'bot') {
    // Search engines
    if (row.bot_category === 'search_engine') {
      if (row.bot_name?.includes('Google')) return '🔍 Google'
      if (row.bot_name?.includes('Yandex')) return '🔍 Yandex'
      if (row.bot_name?.includes('bing')) return '🔍 Bing'
      if (row.bot_name?.includes('DuckDuck')) return '🔍 DuckDuckGo'
      if (row.bot_name?.includes('Baidu')) return '🔍 Baidu'
      if (row.bot_name?.includes('facebook')) return '🔍 Facebook'
      return '🔍 ' + (row.bot_name || 'Пошукова система')
    }

    // SEO tools
    if (row.bot_category === 'seo_tool') {
      return '📊 ' + (row.bot_name || 'SEO')
    }

    // Monitoring
    if (row.bot_category === 'monitoring') {
      return '🔔 ' + (row.bot_name || 'Моніторинг')
    }

    // Bad bots
    if (row.bot_category === 'scraper') {
      return '🤖 Scraper'
    }

    if (row.bot_category === 'malicious') {
      return '🚫 ' + (row.bot_name || 'Malicious')
    }

    return '🤖 Бот'
  }

  // Suspicious
  if (row.client_type === 'suspicious') {
    return '⚠️ Підозрілий'
  }

  // Unknown
  if (row.client_type === 'unknown') {
    return '❓ Невідомий'
  }

  return '⏳ Не класифіковано'
}

function clientTypeBadge(type) {
  const badges = {
    human: 'badge bg-success',
    bot: 'badge bg-secondary',
    suspicious: 'badge bg-warning text-dark',
    unknown: 'badge bg-info',
  }
  return badges[type] || 'badge bg-light text-dark'
}

function changeClientType(id, currentType) {
  window.dispatchEvent(
    new CustomEvent('open-change-client-type', {
      detail: { id, currentType }
    })
  )
}

function toggleSelect(id) {
  const idx = selected.value.indexOf(id)
  if (idx > -1) {
    selected.value.splice(idx, 1)
  } else {
    selected.value.push(id)
  }
}

function toggleSelectAll() {
  if (isAllSelected.value) {
    selected.value = []
  } else {
    selected.value = items.value.map(row => row.id)
  }
}

function clearSelection() {
  selected.value = []
  bulkClientType.value = ''
}

async function applyBulkChange() {
  if (!bulkClientType.value || selected.value.length === 0) return

  if (!confirm(`Змінити тип для ${selected.value.length} записів на "${clientTypeLabel(bulkClientType.value)}"?`)) return

  try {
    const res = await fetch('/api/admin/analytics/bulk-update-client-type', {
      method: 'PATCH',
      headers: { ...authHeaders(), 'Content-Type': 'application/json' },
      body: JSON.stringify({
        ids: selected.value,
        client_type: bulkClientType.value
      })
    })

    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = await res.json()

    if (json.status === 'success') {
      clearSelection()
      load(page.value)
    } else {
      notify('Помилка: ' + (json.message || 'Невідома помилка'), { type: 'error' })
    }
  } catch (e) {
    notify('Помилка: ' + e.message, { type: 'error' })
  }
}

async function showMyIp() {
  try {
    const res = await fetch('/api/admin/network-tools/my-ip', { headers: authHeaders() })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = await res.json()
    if (json.status === 'success' && json.data?.ip) {
      const ip = json.data.ip
      const ipParts = ip.split('.')
      const subnet = ipParts.slice(0, 3).join('.') + '.*'
      const message = `Ваш IP: ${ip}\n\nДодати до виключень в .env:\n` +
        `ANALYTICS_EXCLUDED_IPS=${ip}\n\n` +
        `Або всю підмережу:\nANALYTICS_EXCLUDED_IPS=${subnet}\n\n` +
        `Підтримуються wildcard: 192.168.8.*, 10.0.*.*`
      if (confirm(message + '\n\nСкопіювати IP у фільтр?')) {
        ipFilter.value = ip
        load(1)
      }
    } else {
      notify('Не вдалося отримати IP: ' + (json.message || 'Невідома помилка'), { type: 'error' })
    }
  } catch (e) {
    notify('Помилка: ' + e.message, { type: 'error' })
  }
}

onMounted(() => {
  // Инициализируем фильтры из URL перед первой загрузкой
  initFromUrl()
  load(page.value)

  // Listen for details modal closed
  window.addEventListener('analytics-details-closed', () => {
    detailId.value = null
  })

  // Listen for IP filter event from modal
  window.addEventListener('filter-analytics-by-ip', (e) => {
    if (e.detail?.ip) {
      filterByIp(e.detail.ip)
    }
  })

  // Listen for client type selection
  window.addEventListener('client-type-selected', async (e) => {
    if (!e.detail?.id || !e.detail?.newType) return

    try {
      const res = await fetch(`/api/admin/analytics/pageview/${e.detail.id}/client-type`, {
        method: 'PATCH',
        headers: { ...authHeaders(), 'Content-Type': 'application/json' },
        body: JSON.stringify({ client_type: e.detail.newType })
      })

      if (!res.ok) throw new Error(`HTTP ${res.status}`)
      const json = await res.json()

      if (json.status === 'success') {
        load(page.value) // Перезагрузить текущую страницу
      } else {
        notify('Помилка: ' + (json.message || 'Невідома помилка'), { type: 'error' })
      }
    } catch (err) {
      notify('Помилка: ' + err.message, { type: 'error' })
    }
  })
})
</script>

<style scoped>
/* Page content wrapper with scroll */
.th-sortable {
  cursor: pointer;
  user-select: none;
}
.th-sortable:hover {
  background-color: rgba(0, 0, 0, 0.05);
}
</style>

// frontend-react/src/pages/Analytics.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import Pagination from '@/list-framework/components/Pagination'
import AnalyticsDetailsModal from './AnalyticsDetailsModal'
import ChangeClientTypeModal from './ChangeClientTypeModal'
import { apiGet, apiPatch } from '@/utils/api'
import { notify } from '@/hooks/useNotify'
import { formatDate } from '@/utils/date'
import {
  useUrlFilters,
  readFiltersFromUrl,
  readSortFromUrl,
  readDetailIdFromUrl,
} from '@/hooks/useUrlFilters'
import { CLIENT_TYPE_BADGE, responseTimeClass } from './analyticsLabels'
import { methodBadge, rowClass, shortReferer, smartClientLabel, statusBadge } from './analyticsBadges'

const PER_PAGE = 100

const CLIENT_TYPE_GROUPS = [
  {
    label: '👤 Люди',
    options: [
      { value: 'human', label: 'Всі люди' },
      { value: 'human_desktop', label: '🖥️ Desktop' },
      { value: 'human_mobile', label: '📱 Mobile' },
      { value: 'human_tablet', label: '📲 Tablet' },
      { value: 'human_unknown', label: '❓ Невідомі' },
    ],
  },
  {
    label: '🔍 Пошукові системи',
    options: [
      { value: 'bot_search_engine', label: 'Всі пошукові системи' },
      { value: 'bot_search_google', label: 'Google' },
      { value: 'bot_search_yandex', label: 'Yandex' },
      { value: 'bot_search_bing', label: 'Bing' },
      { value: 'bot_search_other', label: 'Інші' },
      { value: 'bot_search_unknown', label: '❓ Невідомі' },
    ],
  },
  {
    label: '📊 SEO інструменти',
    options: [
      { value: 'bot_seo_tool', label: 'Всі SEO інструменти' },
      { value: 'bot_seo_unknown', label: '❓ Невідомі' },
    ],
  },
  {
    label: '🔔 Моніторинг',
    options: [
      { value: 'bot_monitoring', label: 'Всі моніторинг-сервіси' },
      { value: 'bot_monitoring_unknown', label: '❓ Невідомі' },
    ],
  },
  {
    label: '🚫 Погані боти',
    options: [
      { value: 'bot_scraper', label: '🤖 Scrapers' },
      { value: 'bot_malicious', label: '⚠️ Malicious (сканери)' },
      { value: 'bot_bad_unknown', label: '❓ Невідомі' },
    ],
  },
  {
    label: 'Інше',
    options: [
      { value: 'suspicious', label: '⚠️ Підозрілі' },
      { value: 'unknown', label: '❓ Невідомі' },
      { value: 'unclassified', label: '⏳ Не проаналізовані' },
    ],
  },
]

const STATUS_OPTIONS = ['200 OK', '201 Created', '204 No Content', '301 Moved', '302 Found',
  '400 Bad Request', '401 Unauthorized', '403 Forbidden', '404 Not Found',
  '422 Unprocessable', '500 Server Error', '503 Unavailable']

const SORT_COLUMNS: Array<{ key: string; label: string; width?: string; align?: string }> = [
  { key: 'id', label: 'ID', width: '60px', align: 'text-end' },
  { key: 'path', label: 'URL' },
  { key: 'method', label: 'Method', width: '60px' },
  { key: 'status_code', label: 'Status', width: '70px' },
  { key: 'ip', label: 'IP', width: '130px' },
  { key: 'referer', label: 'Referer' },
  { key: 'client_type', label: 'Тип / Device', width: '140px' },
  { key: 'browser', label: 'Browser' },
  { key: 'user_id', label: 'User' },
  { key: 'response_time', label: 'Time', width: '90px', align: 'text-end' },
  { key: 'created_at', label: 'Дата', width: '140px' },
]

export default function Analytics() {
  // Початковий стан — з URL (client_type за замовчуванням 'human', як у Vue)
  const urlFilters = readFiltersFromUrl({
    search: '',
    client_type: 'human',
    device_type: '',
    status_code: '',
    method: '',
    date_from: '',
    date_to: '',
    ip: '',
    page: 1,
  })
  const urlSort = readSortFromUrl({ sortKey: 'created_at', sortDir: 'DESC' })

  const [items, setItems] = useState<any[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [page, setPage] = useState(urlFilters.page)
  const [total, setTotal] = useState(0)

  const [search, setSearch] = useState(urlFilters.search)
  const [searchDebounced, setSearchDebounced] = useState(urlFilters.search)
  const [clientTypeFilter, setClientTypeFilter] = useState(urlFilters.client_type)
  const [deviceFilter, setDeviceFilter] = useState(urlFilters.device_type)
  const [statusFilter, setStatusFilter] = useState(urlFilters.status_code)
  const [methodFilter, setMethodFilter] = useState(urlFilters.method)
  const [dateFrom, setDateFrom] = useState(urlFilters.date_from)
  const [dateTo, setDateTo] = useState(urlFilters.date_to)
  const [ipFilter, setIpFilter] = useState(urlFilters.ip)
  const [ipFilterDebounced, setIpFilterDebounced] = useState(urlFilters.ip)

  const [sortKey, setSortKey] = useState(urlSort.sortKey)
  const [sortDir, setSortDir] = useState<'ASC' | 'DESC'>(urlSort.sortDir as 'ASC' | 'DESC')
  const [selected, setSelected] = useState<number[]>([])
  const [bulkClientType, setBulkClientType] = useState('')
  const [detailId, setDetailId] = useState<number | null>(() => readDetailIdFromUrl())
  const [changeType, setChangeType] = useState<{ id: number; currentType: string } | null>(null)

  useUrlFilters({
    filters: {
      search,
      client_type: clientTypeFilter,
      device_type: deviceFilter,
      status_code: statusFilter,
      method: methodFilter,
      date_from: dateFrom,
      date_to: dateTo,
      ip: ipFilter,
      page: page > 1 ? page : '',
    },
    sorting: { sortKey, sortDir },
    detailId,
  })

  const debounceRef = useRef<ReturnType<typeof setTimeout>>()
  useEffect(() => {
    clearTimeout(debounceRef.current)
    debounceRef.current = setTimeout(() => {
      setSearchDebounced(search)
      setIpFilterDebounced(ipFilter)
      setPage(1)
    }, 400)
    return () => clearTimeout(debounceRef.current)
  }, [search, ipFilter])

  const load = useCallback(async () => {
    setLoading(true)
    setError('')

    const params = new URLSearchParams({
      page: String(page),
      per_page: String(PER_PAGE),
      sort_by: sortKey,
      sort_dir: sortDir,
    })
    if (searchDebounced) params.set('search', searchDebounced)
    if (clientTypeFilter) params.set('client_type', clientTypeFilter)
    if (deviceFilter) params.set('device_type', deviceFilter)
    if (statusFilter) params.set('status_code', statusFilter)
    if (methodFilter) params.set('method', methodFilter)
    if (dateFrom) params.set('date_from', dateFrom)
    if (dateTo) params.set('date_to', dateTo)
    if (ipFilterDebounced) params.set('ip', ipFilterDebounced)

    try {
      const res = await apiGet(`/admin/analytics/pageviews?${params}`)
      setItems(res.data ?? [])
      setTotal(res.pagination?.total ?? 0)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Помилка завантаження')
    } finally {
      setLoading(false)
    }
  }, [page, sortKey, sortDir, searchDebounced, clientTypeFilter, deviceFilter,
      statusFilter, methodFilter, dateFrom, dateTo, ipFilterDebounced])

  useEffect(() => { load() }, [load])

  const totalPages = Math.ceil(total / PER_PAGE)
  const isAllSelected = items.length > 0 && items.every(row => selected.includes(row.id))

  const toggleSort = (col: string) => {
    if (sortKey === col) setSortDir(d => (d === 'ASC' ? 'DESC' : 'ASC'))
    else { setSortKey(col); setSortDir('DESC') }
    setPage(1)
  }

  const sortIcon = (col: string) => {
    if (sortKey !== col) return <i className="bi bi-arrow-down-up text-muted opacity-25 ms-1" />
    return <i className={`bi bi-arrow-${sortDir === 'ASC' ? 'up' : 'down'} text-primary ms-1`} />
  }

  const clearSelection = () => { setSelected([]); setBulkClientType('') }

  const applyBulkChange = async () => {
    if (!bulkClientType || selected.length === 0) return
    try {
      await apiPatch('/admin/analytics/bulk-update-client-type', {
        ids: selected,
        client_type: bulkClientType,
      })
      clearSelection()
      load()
    } catch (err) {
      notify(`Помилка: ${err instanceof Error ? err.message : 'невідома'}`, { type: 'error' })
    }
  }

  const applyClientType = async (newType: string) => {
    if (!changeType) return
    try {
      await apiPatch(`/admin/analytics/pageview/${changeType.id}/client-type`, { client_type: newType })
      setChangeType(null)
      load()
    } catch (err) {
      notify(`Помилка: ${err instanceof Error ? err.message : 'невідома'}`, { type: 'error' })
    }
  }

  const showMyIp = async () => {
    try {
      const res = await apiGet('/admin/network-tools/my-ip')
      const ip = res.data?.ip
      if (!ip) {
        notify('Не вдалося отримати IP', { type: 'error' })
        return
      }
      const subnet = ip.split('.').slice(0, 3).join('.') + '.*'
      notify(
        `Ваш IP: ${ip}\n\nДодати до виключень в .env:\nANALYTICS_EXCLUDED_IPS=${ip}\n` +
        `Або всю підмережу: ${subnet}`,
        { type: 'info', duration: 10000, action: { label: 'У фільтр', onClick: () => setIpFilter(ip) } }
      )
    } catch (err) {
      notify(`Помилка: ${err instanceof Error ? err.message : 'невідома'}`, { type: 'error' })
    }
  }

  return (
    <div>
      <div className="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
        <div className="d-flex align-items-center gap-2">
          <h5 className="mb-0">Аналітика відвідувань</h5>
          <Link to="/analytics/stats" className="btn btn-sm btn-outline-primary">
            <i className="bi bi-bar-chart" /> Статистика
          </Link>
          <Link to="/analytics/charts" className="btn btn-sm btn-outline-primary">
            <i className="bi bi-graph-up-arrow" /> Графіки
          </Link>
        </div>

        <div className="d-flex gap-2 flex-wrap">
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            type="text"
            className="form-control form-control-sm"
            style={{ width: '200px' }}
            placeholder="Пошук..."
          />
          <select
            value={clientTypeFilter}
            onChange={(e) => { setClientTypeFilter(e.target.value); setPage(1) }}
            className="form-select form-select-sm"
            style={{ width: '220px' }}
          >
            <option value="">Всі типи клієнтів</option>
            {CLIENT_TYPE_GROUPS.map(group => (
              <optgroup key={group.label} label={group.label}>
                {group.options.map(o => <option key={o.value} value={o.value}>{o.label}</option>)}
              </optgroup>
            ))}
          </select>
          <select
            value={deviceFilter}
            onChange={(e) => { setDeviceFilter(e.target.value); setPage(1) }}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            <option value="">Всі пристрої</option>
            <option value="desktop">Desktop</option>
            <option value="mobile">Mobile</option>
            <option value="tablet">Tablet</option>
          </select>
          <select
            value={statusFilter}
            onChange={(e) => { setStatusFilter(e.target.value); setPage(1) }}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            <option value="">Всі статуси</option>
            {STATUS_OPTIONS.map(s => {
              const code = s.split(' ')[0]
              return <option key={code} value={code}>{s}</option>
            })}
            <option value="other">Інші статуси</option>
          </select>
          <select
            value={methodFilter}
            onChange={(e) => { setMethodFilter(e.target.value); setPage(1) }}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            <option value="">Всі методи</option>
            {['GET', 'POST', 'PUT', 'PATCH', 'DELETE'].map(m => <option key={m} value={m}>{m}</option>)}
            <option value="other">Інші методи</option>
          </select>
          <input
            value={dateFrom}
            onChange={(e) => { setDateFrom(e.target.value); setPage(1) }}
            type="date"
            className="form-control form-control-sm"
            style={{ width: 'auto' }}
          />
          <input
            value={dateTo}
            onChange={(e) => { setDateTo(e.target.value); setPage(1) }}
            type="date"
            className="form-control form-control-sm"
            style={{ width: 'auto' }}
          />
          <div className="input-group" style={{ width: 'auto' }}>
            <input
              value={ipFilter}
              onChange={(e) => setIpFilter(e.target.value)}
              type="text"
              className="form-control form-control-sm"
              style={{ width: '150px' }}
              placeholder="IP адреса..."
            />
            <button
              className="btn btn-sm btn-outline-secondary"
              type="button"
              title="Показати мій IP"
              onClick={showMyIp}
            >
              <i className="bi bi-hdd-network" />
            </button>
          </div>
        </div>
      </div>

      {/* Масові дії */}
      {selected.length > 0 && (
        <div className="alert alert-info d-flex align-items-center gap-2 mb-3">
          <span><strong>{selected.length}</strong> обрано</span>
          <select
            value={bulkClientType}
            onChange={(e) => setBulkClientType(e.target.value)}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            <option value="">Змінити тип на...</option>
            <option value="human">👤 Людина</option>
            <option value="bot">🤖 Бот</option>
            <option value="suspicious">⚠️ Підозрілий</option>
            <option value="unknown">❓ Невідомий</option>
          </select>
          <button className="btn btn-sm btn-primary" disabled={!bulkClientType} onClick={applyBulkChange}>
            Застосувати
          </button>
          <button className="btn btn-sm btn-outline-secondary" onClick={clearSelection}>Скасувати</button>
        </div>
      )}

      {loading && <div className="text-center py-5"><div className="spinner-border text-primary" /></div>}
      {!loading && error && <div className="alert alert-danger">{error}</div>}

      {!loading && !error && (
        <>
          <div className="card shadow-sm">
            <div className="table-responsive">
              <table className="table table-hover align-middle mb-0 small">
                <thead className="table-light">
                  <tr>
                    <th style={{ width: '40px' }}>
                      <input
                        type="checkbox"
                        className="form-check-input"
                        checked={isAllSelected}
                        onChange={() => setSelected(isAllSelected ? [] : items.map(r => r.id))}
                        title="Вибрати всі"
                      />
                    </th>
                    {SORT_COLUMNS.map(col => (
                      <th
                        key={col.key}
                        style={col.width ? { width: col.width } : undefined}
                        className={`th-sortable ${col.align ?? ''}`}
                        onClick={() => toggleSort(col.key)}
                      >
                        {col.label} {sortIcon(col.key)}
                      </th>
                    ))}
                    <th style={{ width: '80px' }} />
                  </tr>
                </thead>
                <tbody>
                  {items.map(row => (
                    <tr key={row.id} className={rowClass(row.status_code)}>
                      <td>
                        <input
                          type="checkbox"
                          className="form-check-input"
                          checked={selected.includes(row.id)}
                          onChange={() => setSelected(prev =>
                            prev.includes(row.id) ? prev.filter(i => i !== row.id) : [...prev, row.id]
                          )}
                        />
                      </td>
                      <td className="text-muted text-end">{row.id}</td>
                      <td>
                        <div className="text-truncate" style={{ maxWidth: '300px' }} title={row.path}>
                          {row.path}
                        </div>
                      </td>
                      <td><span className={methodBadge(row.method)}>{row.method}</span></td>
                      <td><span className={statusBadge(row.status_code)}>{row.status_code}</span></td>
                      <td className="small">
                        <a
                          href="#"
                          className="text-decoration-none"
                          title={`Фільтрувати за IP: ${row.ip}`}
                          onClick={(e) => { e.preventDefault(); setIpFilter(row.ip) }}
                        >
                          <i className="bi bi-filter-circle" /> {row.ip}
                        </a>
                      </td>
                      <td className="text-muted small">
                        <div className="text-truncate" style={{ maxWidth: '200px' }} title={row.referer}>
                          {shortReferer(row.referer)}
                        </div>
                      </td>
                      <td>
                        <span
                          className={CLIENT_TYPE_BADGE[row.client_type] ?? 'badge bg-light text-dark'}
                          style={{ cursor: 'pointer' }}
                          title={`Клік щоб змінити тип. Метод: ${row.detection_method || 'не вказано'}`}
                          onClick={() => setChangeType({ id: row.id, currentType: row.client_type })}
                        >
                          {smartClientLabel(row)}
                        </span>
                      </td>
                      <td className="text-muted small">{row.browser || '—'}</td>
                      <td className="text-muted small">
                        {row.user_id
                          ? <span title={row.email}>#{row.user_id} {row.username}</span>
                          : '—'}
                      </td>
                      <td className="text-end">
                        <span className={responseTimeClass(row.response_time)}>{row.response_time}ms</span>
                      </td>
                      <td className="text-muted" style={{ whiteSpace: 'nowrap' }}>
                        {formatDate(row.created_at)}
                      </td>
                      <td className="text-center">
                        <button
                          className="btn btn-sm btn-outline-primary"
                          title="Детальна інформація"
                          onClick={() => setDetailId(row.id)}
                        >
                          <i className="bi bi-info-circle" />
                        </button>
                      </td>
                    </tr>
                  ))}
                  {items.length === 0 && (
                    <tr><td colSpan={14} className="text-center text-muted py-4">Немає даних</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          <div className="d-flex justify-content-between align-items-center mt-3">
            <span className="text-muted small">Всього: {total}</span>
            {totalPages > 1 && (
              <Pagination currentPage={page} totalPages={totalPages} onChange={setPage} />
            )}
          </div>
        </>
      )}

      {detailId !== null && (
        <AnalyticsDetailsModal
          id={detailId}
          onClose={() => setDetailId(null)}
          onFilterByIp={(ip) => { setIpFilter(ip); setDetailId(null) }}
        />
      )}

      {changeType && (
        <ChangeClientTypeModal
          currentType={changeType.currentType}
          onSelect={applyClientType}
          onClose={() => setChangeType(null)}
        />
      )}
    </div>
  )
}
