// frontend/src/pages/Dashboard.vue
<template>
  <BaseLayout>
    <h5 class="mb-4">Панель управління</h5>
    <SystemHealthWidget v-if="auth.can(P.system.monitoringView)" />
    <div class="row g-3">
      <div v-for="section in visibleMenu" :key="section.id" class="col-sm-6 col-lg-3">
        <div class="card h-100 shadow-sm">
          <div class="card-body d-flex flex-column">
            <div class="mb-3">
              <i :class="['bi', section.icon, 'fs-2', 'text-primary']"></i>
            </div>
            <h6 class="card-title">{{ section.label }}</h6>
            <ul class="list-unstyled mt-auto mb-0">
              <li v-for="item in section.items.filter(i => auth.can(i.permission))" :key="item.to">
                <router-link :to="item.to" class="text-decoration-none small">
                  <i :class="['bi', item.icon, 'me-1', 'text-muted']"></i>
                  {{ item.label }}
                </router-link>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </BaseLayout>
</template>

<script setup>
import { computed } from 'vue'
import { useAuth } from '@/composables/useAuth'
import BaseLayout from '@/layouts/BaseLayout.vue'
import SystemHealthWidget from '@/components/SystemHealthWidget.vue'
import menu from '@/config/menu.json'
import P from '@/config/permissions'

const auth = useAuth()

const visibleMenu = computed(() =>
  menu.filter(s => auth.can(s.permission))
)
</script>

// frontend-react/src/pages/Dashboard.tsx
import { Link } from 'react-router-dom'
import SystemHealthWidget from '@/components/SystemHealthWidget'
import { useAuth } from '@/contexts/AuthContext'
import menuConfig from '@/config/menu.json'

interface MenuItem {
  label: string
  to: string
  icon: string
  permission: string
  roles: string[]
}

interface MenuSection {
  id: string
  label: string
  icon: string
  permission: string
  roles: string[]
  items: MenuItem[]
}

export default function Dashboard() {
  const { can } = useAuth()
  const menu = menuConfig as MenuSection[]

  const visibleMenu = menu.filter(
    s => can(s.permission) || s.items.some(i => can(i.permission))
  )

  return (
    <div>
      <h5 className="mb-4">Панель управління</h5>

      {can('system.monitoring.view') && <SystemHealthWidget />}

      <div className="row g-3">
        {visibleMenu.map(section => (
          <div key={section.id} className="col-sm-6 col-lg-3">
            <div className="card h-100 shadow-sm">
              <div className="card-body d-flex flex-column">
                <div className="mb-3">
                  <i className={`bi ${section.icon} fs-2 text-primary`} />
                </div>
                <h6 className="card-title">{section.label}</h6>
                <ul className="list-unstyled mt-auto mb-0">
                  {section.items.filter(i => can(i.permission)).map(item => (
                    <li key={item.to}>
                      <Link to={item.to} className="text-decoration-none small">
                        <i className={`bi ${item.icon} me-1 text-muted`} />
                        {item.label}
                      </Link>
                    </li>
                  ))}
                </ul>
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  )
}
