// frontend/src/pages/ErrorLogs.vue
<template>
  <ErrorLogDetailModal />
  <ErrorLogCleanupModal />
  <ListPageWrapper>
    <div>
      <div class="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
        <div class="d-flex align-items-center gap-2">
          <h5 class="mb-0">Логи помилок</h5>
          <router-link to="/error-logs/stats" class="btn btn-sm btn-outline-primary">
            <i class="bi bi-bar-chart"></i> Статистика
          </router-link>
        </div>
        <div class="d-flex gap-2 flex-wrap">
          <input
            v-model="search"
            type="text"
            class="form-control form-control-sm"
            style="width:220px"
            placeholder="Пошук..."
            @input="debounceLoad"
          />
          <select v-model="filterLevel" class="form-select form-select-sm" style="width:auto" @change="load(1)">
            <option value="">Всі рівні</option>
            <option value="error">Error</option>
            <option value="critical">Critical</option>
            <option value="warning">Warning</option>
            <option value="alert">Alert</option>
            <option value="emergency">Emergency</option>
          </select>
          <input
            v-model="filterDateFrom"
            type="date"
            class="form-control form-control-sm"
            style="width:auto"
            @change="load(1)"
          />
          <input
            v-model="filterDateTo"
            type="date"
            class="form-control form-control-sm"
            style="width:auto"
            @change="load(1)"
          />
          <button class="btn btn-sm btn-outline-danger" @click="openCleanup">
            <i class="bi bi-trash"></i> Очистити
          </button>
        </div>
      </div>

      <div v-if="loading" class="text-center py-5">
        <div class="spinner-border text-primary" role="status"></div>
      </div>
      <div v-else-if="error" class="alert alert-danger">{{ error }}</div>

      <div v-else>
        <div class="card shadow-sm">
        <div class="table-responsive">
          <table class="table table-hover align-middle mb-0 small">
            <thead class="table-light">
              <tr>
                <th style="width:60px" class="text-end">ID</th>
                <th style="width:90px" class="th-sortable" @click="toggleSort('level')">
                  Рівень <SortIcon col="level" :sortKey :sortDir />
                </th>
                <th>Категорія</th>
                <th>Повідомлення</th>
                <th>Exception</th>
                <th>Файл</th>
                <th style="width:140px" class="th-sortable" @click="toggleSort('created_at')">
                  Дата <SortIcon col="created_at" :sortKey :sortDir />
                </th>
                <th style="width:50px"></th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="row in items" :key="row.id" :class="rowClass(row.level)">
                <td class="text-muted text-end">{{ row.id }}</td>
                <td><span :class="levelBadge(row.level)">{{ row.level }}</span></td>
                <td class="text-muted small">{{ row.category || '—' }}</td>
                <td>
                  <div class="text-truncate" style="max-width: 400px" :title="row.message">
                    {{ row.message }}
                  </div>
                </td>
                <td class="text-muted small">
                  <div class="text-truncate" style="max-width: 250px" :title="row.exception_class">
                    {{ shortException(row.exception_class) }}
                  </div>
                </td>
                <td class="text-muted small">
                  <div class="text-truncate" style="max-width: 200px" :title="row.file">
                    {{ shortFile(row.file) }}<span v-if="row.line">:{{ row.line }}</span>
                  </div>
                </td>
                <td class="text-muted" style="white-space:nowrap">
                  {{ formatDate(row.created_at) }}
                </td>
                <td>
                  <button class="btn btn-sm btn-outline-secondary" @click="openDetail(row.id)" title="Детальна інформація">
                    <i class="bi bi-eye"></i>
                  </button>
                </td>
              </tr>
              <tr v-if="!items.length">
                <td colspan="8" class="text-center text-muted py-4">Немає даних</td>
              </tr>
            </tbody>
          </table>
          </div>
        </div>

        <div class="d-flex justify-content-between align-items-center mt-3">
          <span class="text-muted small">Всього: {{ total }}</span>
          <Pagination :current-page="page" :total-pages="totalPages" @change="load" />
        </div>
      </div>
    </div>
    </ListPageWrapper>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { authHeaders } from '@/utils/api'
import ListPageWrapper from '../components/ListPageWrapper.vue'
import SortIcon from '../components/SortIcon.vue'
import Pagination from '../components/Pagination.vue'
import ErrorLogDetailModal from '../components/ErrorLogDetailModal.vue'
import ErrorLogCleanupModal from '../components/ErrorLogCleanupModal.vue'
import { useUrlFilters } from '../composables/useUrlFilters'
import { formatDate } from '../utils/date'

const items = ref([])
const loading = ref(false)
const error = ref('')
const page = ref(1)
const perPage = ref(50)
const total = ref(0)
const search = ref('')
const filterLevel = ref('')
const filterDateFrom = ref('')
const filterDateTo = ref('')
const sortKey = ref('created_at')
const sortDir = ref('DESC')
const detailId = ref(null)

// Синхронизация с URL
const { initFromUrl } = useUrlFilters({
  filters: {
    search,
    level: filterLevel,
    date_from: filterDateFrom,
    date_to: filterDateTo,
    page
  },
  sorting: {
    sortKey,
    sortDir
  },
  detail: {
    id: detailId,
    onOpen: (id) => {
      window.dispatchEvent(new CustomEvent('open-error-log-detail', { detail: { id } }))
    }
  }
})


const totalPages = computed(() => Math.ceil(total.value / perPage.value))


async function load(p = 1) {
  loading.value = true
  error.value = ''
  page.value = p

  const params = new URLSearchParams({
    page: page.value,
    per_page: perPage.value,
    sort_by: sortKey.value,
    sort_dir: sortDir.value,
  })
  if (search.value) params.set('search', search.value)
  if (filterLevel.value) params.set('level', filterLevel.value)
  if (filterDateFrom.value) params.set('date_from', filterDateFrom.value)
  if (filterDateTo.value) params.set('date_to', filterDateTo.value)

  try {
    const res = await fetch(`/api/admin/error-logs?${params}`, { headers: authHeaders() })
    if (!res.ok) throw new Error(`HTTP ${res.status}`)
    const json = await res.json()
    if (json.status === 'success') {
      items.value = json.data
      total.value = json.pagination.total
    } else {
      error.value = json.message || 'Помилка завантаження'
    }
  } catch (e) {
    error.value = e.message
  } finally {
    loading.value = false
  }
}

function toggleSort(col) {
  if (sortKey.value === col) {
    sortDir.value = sortDir.value === 'ASC' ? 'DESC' : 'ASC'
  } else {
    sortKey.value = col
    sortDir.value = 'DESC'
  }
  load(1)
}

let debounceTimer
function debounceLoad() {
  clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => load(1), 400)
}

function openDetail(id) {
  detailId.value = id
  window.dispatchEvent(new CustomEvent('open-error-log-detail', { detail: { id } }))
}

function openCleanup() {
  window.dispatchEvent(new CustomEvent('open-error-log-cleanup'))
}

function levelBadge(level) {
  const map = {
    error: 'badge bg-danger',
    critical: 'badge bg-danger',
    alert: 'badge bg-warning text-dark',
    emergency: 'badge bg-dark',
    warning: 'badge bg-warning text-dark',
  }
  return map[level] || 'badge bg-secondary'
}

function rowClass(level) {
  if (level === 'critical' || level === 'emergency') return 'table-danger'
  if (level === 'error') return 'table-warning'
  return ''
}

function shortException(str) {
  if (!str) return '—'
  const parts = str.split('\\')
  return parts[parts.length - 1]
}

function shortFile(str) {
  if (!str) return '—'
  const parts = str.split('/')
  return parts.slice(-2).join('/')
}


onMounted(() => {
  initFromUrl()
  load(page.value)

  // Listen for detail closed
  window.addEventListener('error-log-detail-closed', () => {
    detailId.value = null
  })

  // Listen for cleanup event
  window.addEventListener('error-logs-cleaned', () => {
    load(page.value)
  })
})
</script>

<style scoped>
.th-sortable {
  cursor: pointer;
  user-select: none;
}
.th-sortable:hover {
  background-color: rgba(0, 0, 0, 0.05);
}
</style>

// frontend-react/src/pages/ErrorLogs.tsx
import { useCallback, useEffect, useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import Pagination from '@/list-framework/components/Pagination'
import ErrorLogDetailModal from './ErrorLogDetailModal'
import ErrorLogCleanupModal from './ErrorLogCleanupModal'
import { LEVEL_BADGE, rowClass, shortException, shortFile } from './errorLogLevels'
import { apiGet } from '@/utils/api'
import { formatDate } from '@/utils/date'
import {
  useUrlFilters,
  readFiltersFromUrl,
  readSortFromUrl,
  readDetailIdFromUrl,
} from '@/hooks/useUrlFilters'

interface ErrorLog {
  id: number
  level: string
  category: string | null
  message: string
  exception_class: string | null
  file: string | null
  line: number | null
  created_at: string
}

const PER_PAGE = 50
const LEVELS = ['error', 'critical', 'warning', 'alert', 'emergency']

export default function ErrorLogs() {
  // Початковий стан — з URL, щоб посилання на відфільтрований список працювало
  const urlFilters = readFiltersFromUrl({ search: '', level: '', date_from: '', date_to: '', page: 1 })
  const urlSort = readSortFromUrl({ sortKey: 'created_at', sortDir: 'DESC' })

  const [items, setItems] = useState<ErrorLog[]>([])
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [page, setPage] = useState(urlFilters.page)
  const [total, setTotal] = useState(0)
  const [search, setSearch] = useState(urlFilters.search)
  const [level, setLevel] = useState(urlFilters.level)
  const [dateFrom, setDateFrom] = useState(urlFilters.date_from)
  const [dateTo, setDateTo] = useState(urlFilters.date_to)
  const [sortKey, setSortKey] = useState(urlSort.sortKey)
  const [sortDir, setSortDir] = useState<'ASC' | 'DESC'>(urlSort.sortDir as 'ASC' | 'DESC')
  const [detailId, setDetailId] = useState<number | null>(() => readDetailIdFromUrl())
  const [cleanupOpen, setCleanupOpen] = useState(false)

  useUrlFilters({
    filters: {
      search,
      level,
      date_from: dateFrom,
      date_to: dateTo,
      page: page > 1 ? page : '',
    },
    sorting: { sortKey, sortDir },
    detailId,
  })

  // Пошук з дебаунсом — окремий стан, щоб не смикати сервер на кожну літеру
  const [searchDebounced, setSearchDebounced] = useState(urlFilters.search)
  const debounceRef = useRef<ReturnType<typeof setTimeout>>()

  useEffect(() => {
    clearTimeout(debounceRef.current)
    debounceRef.current = setTimeout(() => {
      setSearchDebounced(search)
      setPage(1)
    }, 400)
    return () => clearTimeout(debounceRef.current)
  }, [search])

  const load = useCallback(async () => {
    setLoading(true)
    setError('')

    const params = new URLSearchParams({
      page: String(page),
      per_page: String(PER_PAGE),
      sort_by: sortKey,
      sort_dir: sortDir,
    })
    if (searchDebounced) params.set('search', searchDebounced)
    if (level) params.set('level', level)
    if (dateFrom) params.set('date_from', dateFrom)
    if (dateTo) params.set('date_to', dateTo)

    try {
      const res = await apiGet(`/admin/error-logs?${params}`)
      setItems(res.data ?? [])
      setTotal(res.pagination?.total ?? 0)
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Помилка завантаження')
    } finally {
      setLoading(false)
    }
  }, [page, sortKey, sortDir, searchDebounced, level, dateFrom, dateTo])

  useEffect(() => { load() }, [load])

  const totalPages = Math.ceil(total / PER_PAGE)

  const toggleSort = (col: string) => {
    if (sortKey === col) {
      setSortDir(d => (d === 'ASC' ? 'DESC' : 'ASC'))
    } else {
      setSortKey(col)
      setSortDir('DESC')
    }
    setPage(1)
  }

  const sortIcon = (col: string) => {
    if (sortKey !== col) return <i className="bi bi-arrow-down-up text-muted opacity-25 ms-1" />
    return <i className={`bi bi-arrow-${sortDir === 'ASC' ? 'up' : 'down'} text-primary ms-1`} />
  }

  return (
    <div>
      <div className="d-flex flex-wrap gap-2 align-items-center justify-content-between mb-3">
        <div className="d-flex align-items-center gap-2">
          <h5 className="mb-0">Логи помилок</h5>
          <Link to="/error-logs/stats" className="btn btn-sm btn-outline-primary">
            <i className="bi bi-bar-chart" /> Статистика
          </Link>
        </div>
        <div className="d-flex gap-2 flex-wrap">
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            type="text"
            className="form-control form-control-sm"
            style={{ width: '220px' }}
            placeholder="Пошук..."
          />
          <select
            value={level}
            onChange={(e) => { setLevel(e.target.value); setPage(1) }}
            className="form-select form-select-sm"
            style={{ width: 'auto' }}
          >
            <option value="">Всі рівні</option>
            {LEVELS.map(l => (
              <option key={l} value={l}>{l.charAt(0).toUpperCase() + l.slice(1)}</option>
            ))}
          </select>
          <input
            value={dateFrom}
            onChange={(e) => { setDateFrom(e.target.value); setPage(1) }}
            type="date"
            className="form-control form-control-sm"
            style={{ width: 'auto' }}
          />
          <input
            value={dateTo}
            onChange={(e) => { setDateTo(e.target.value); setPage(1) }}
            type="date"
            className="form-control form-control-sm"
            style={{ width: 'auto' }}
          />
          <button className="btn btn-sm btn-outline-danger" onClick={() => setCleanupOpen(true)}>
            <i className="bi bi-trash" /> Очистити
          </button>
        </div>
      </div>

      {loading && (
        <div className="text-center py-5">
          <div className="spinner-border text-primary" />
        </div>
      )}

      {!loading && error && <div className="alert alert-danger">{error}</div>}

      {!loading && !error && (
        <>
          <div className="card shadow-sm">
            <div className="table-responsive">
              <table className="table table-hover align-middle mb-0 small">
                <thead className="table-light">
                  <tr>
                    <th style={{ width: '60px' }} className="text-end">ID</th>
                    <th style={{ width: '90px' }} className="th-sortable" onClick={() => toggleSort('level')}>
                      Рівень {sortIcon('level')}
                    </th>
                    <th>Категорія</th>
                    <th>Повідомлення</th>
                    <th>Exception</th>
                    <th>Файл</th>
                    <th style={{ width: '140px' }} className="th-sortable" onClick={() => toggleSort('created_at')}>
                      Дата {sortIcon('created_at')}
                    </th>
                    <th style={{ width: '50px' }} />
                  </tr>
                </thead>
                <tbody>
                  {items.map(row => (
                    <tr key={row.id} className={rowClass(row.level)}>
                      <td className="text-muted text-end">{row.id}</td>
                      <td><span className={LEVEL_BADGE[row.level] ?? 'badge bg-secondary'}>{row.level}</span></td>
                      <td className="text-muted small">{row.category || '—'}</td>
                      <td>
                        <div className="text-truncate" style={{ maxWidth: '400px' }} title={row.message}>
                          {row.message}
                        </div>
                      </td>
                      <td className="text-muted small">
                        <div className="text-truncate" style={{ maxWidth: '250px' }} title={row.exception_class ?? ''}>
                          {shortException(row.exception_class)}
                        </div>
                      </td>
                      <td className="text-muted small">
                        <div className="text-truncate" style={{ maxWidth: '200px' }} title={row.file ?? ''}>
                          {shortFile(row.file)}{row.line ? `:${row.line}` : ''}
                        </div>
                      </td>
                      <td className="text-muted" style={{ whiteSpace: 'nowrap' }}>
                        {formatDate(row.created_at)}
                      </td>
                      <td>
                        <button
                          className="btn btn-sm btn-outline-secondary"
                          title="Детальна інформація"
                          onClick={() => setDetailId(row.id)}
                        >
                          <i className="bi bi-eye" />
                        </button>
                      </td>
                    </tr>
                  ))}
                  {items.length === 0 && (
                    <tr><td colSpan={8} className="text-center text-muted py-4">Немає даних</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>

          <div className="d-flex justify-content-between align-items-center mt-3">
            <span className="text-muted small">Всього: {total}</span>
            {totalPages > 1 && (
              <Pagination currentPage={page} totalPages={totalPages} onChange={setPage} />
            )}
          </div>
        </>
      )}

      {detailId !== null && (
        <ErrorLogDetailModal id={detailId} onClose={() => setDetailId(null)} />
      )}

      {cleanupOpen && (
        <ErrorLogCleanupModal onClose={() => setCleanupOpen(false)} onCleaned={load} />
      )}
    </div>
  )
}
