// frontend/src/pages/NotImplemented.vue
<template>
  <div class="text-center text-muted py-5">
    <i :class="`bi ${item?.icon ?? 'bi-cone-striped'}`" style="font-size: 2.5rem" />
    <h5 class="mt-3 mb-1">{{ item?.label ?? 'Розділ не знайдено' }}</h5>
    <div v-if="section" class="small mb-3">{{ section.label }}</div>
    <p class="small mb-4">
      <template v-if="item">
        Цей розділ ще не реалізовано.
      </template>
      <template v-else>
        Такої сторінки немає: <code>{{ $route.path }}</code>
      </template>
    </p>
    <router-link to="/dashboard" class="btn btn-sm btn-outline-secondary">
      <i class="bi bi-arrow-left me-1" />
      До панелі управління
    </router-link>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute } from 'vue-router'
import menuConfig from '@/config/menu.json'

const route = useRoute()

const section = computed(() =>
  menuConfig.find(s => s.items.some(i => i.to === route.path))
)

const item = computed(() =>
  section.value?.items.find(i => i.to === route.path)
)
</script>

// frontend-react/src/pages/NotImplemented.tsx
import { Link, useLocation } from 'react-router-dom'
import menuConfig from '@/config/menu.json'

interface MenuItem { label: string; to: string; icon: string }
interface MenuSection { id: string; label: string; icon: string; items: MenuItem[] }

/**
 * Меню на дашборді та у верхній панелі будується з menu.json — того самого, що й
 * у Vue-версії, щоб вигляд збігався. Але маршрути в React-порті поки реалізовані
 * не всі, тож замість білої порожнечі показуємо, що саме ще не перенесено.
 */
export default function NotImplemented() {
  const { pathname } = useLocation()
  const menu = menuConfig as MenuSection[]

  const section = menu.find(s => s.items.some(i => i.to === pathname))
  const item = section?.items.find(i => i.to === pathname)

  return (
    <div className="text-center text-muted py-5">
      <i className={`bi ${item?.icon ?? 'bi-cone-striped'}`} style={{ fontSize: '2.5rem' }} />
      <h5 className="mt-3 mb-1">{item?.label ?? 'Розділ не знайдено'}</h5>
      {section && <div className="small mb-3">{section.label}</div>}
      <p className="small mb-4">
        {item
          ? 'Цей розділ ще не перенесено в React-версію.'
          : <>Такої сторінки немає: <code>{pathname}</code></>}
      </p>
      <Link to="/dashboard" className="btn btn-sm btn-outline-secondary">
        <i className="bi bi-arrow-left me-1" />
        До панелі управління
      </Link>
    </div>
  )
}
