// frontend/src/components/ColumnSelector.vue
<!-- Copyright (c) 2026 Oleksandr Nosov. MIT License. -->
<template>
  <div ref="rootEl" class="position-relative d-inline-block">
    <button
      type="button"
      class="btn btn-sm btn-outline-secondary"
      :title="hasHidden ? 'Колонки таблиці (частина прихована)' : 'Колонки таблиці'"
      @click="open = !open"
    >
      <i class="bi bi-layout-three-columns"></i>
      <span v-if="hiddenCount" class="badge bg-secondary ms-1 py-0" style="font-size:.65em">
        {{ hiddenCount }}
      </span>
    </button>

    <!-- Дропдаун рукописний, як решта в адмінці: Bootstrap JS ним не керує -->
    <div
      v-if="open"
      class="dropdown-menu show p-2"
      style="top:100%;left:auto;right:0;min-width:210px;max-height:320px;overflow-y:auto;z-index:1050"
    >
      <div v-for="col in hideableColumns" :key="col.key" class="form-check mb-1">
        <input
          :id="`colsel-${uid}-${col.key}`"
          class="form-check-input"
          type="checkbox"
          :checked="isVisible(col.key)"
          @change="emit('toggle', col.key)"
        />
        <label class="form-check-label small" :for="`colsel-${uid}-${col.key}`">
          {{ col.label }}
        </label>
      </div>

      <div v-if="!hideableColumns.length" class="text-muted small px-1">
        Немає колонок, які можна приховати
      </div>

      <template v-if="hideableColumns.length">
        <hr class="my-2" />
        <button
          type="button"
          class="btn btn-sm btn-link p-0 small text-decoration-none"
          :disabled="!hasHidden"
          @click="emit('reset')"
        >
          Скинути
        </button>
      </template>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, onUnmounted, ref } from 'vue'

const props = defineProps({
  // Повний конфіг колонок таблиці; показуємо лише hideable !== false
  columns:   { type: Array,    required: true },
  isVisible: { type: Function, required: true },
  hasHidden: { type: Boolean,  default: false },
})

const emit = defineEmits(['toggle', 'reset'])

// Унікальний префікс для id чекбоксів: на сторінці може бути кілька таблиць
let seq = 0
const uid = ++seq

const open = ref(false)
const rootEl = ref(null)

const hideableColumns = computed(() => props.columns.filter((c) => c.hideable !== false))
const hiddenCount = computed(() => hideableColumns.value.filter((c) => !props.isVisible(c.key)).length)

// Окремої утиліти click-outside у проєкті немає — слухаємо document тут.
function onDocumentMouseDown(e) {
  if (!open.value) return
  if (rootEl.value && !rootEl.value.contains(e.target)) open.value = false
}

function onKeydown(e) {
  if (e.key === 'Escape') open.value = false
}

onMounted(() => {
  document.addEventListener('mousedown', onDocumentMouseDown)
  document.addEventListener('keydown', onKeydown)
})

onUnmounted(() => {
  document.removeEventListener('mousedown', onDocumentMouseDown)
  document.removeEventListener('keydown', onKeydown)
})
</script>

// frontend-react/src/list-framework/components/ColumnSelector.tsx
import { useEffect, useId, useRef, useState } from 'react'
import type { ColumnConfig } from '../types'

interface ColumnSelectorProps {
  /** Повний конфіг колонок таблиці; показуємо лише hideable !== false */
  columns: ColumnConfig[]
  isVisible: (key: string) => boolean
  hasHidden: boolean
  onToggle: (key: string) => void
  onReset: () => void
}

/**
 * Дзеркало Vue-версії frontend/src/components/ColumnSelector.vue —
 * та сама розмітка Bootstrap і та сама поведінка.
 * Дропдаун рукописний: Bootstrap JS ним не керує.
 */
export default function ColumnSelector({
  columns,
  isVisible,
  hasHidden,
  onToggle,
  onReset,
}: ColumnSelectorProps) {
  const [open, setOpen] = useState(false)
  const rootRef = useRef<HTMLDivElement>(null)
  // Унікальний префікс для id чекбоксів: на сторінці може бути кілька таблиць
  const uid = useId()

  const hideableColumns = columns.filter(c => c.hideable !== false)
  const hiddenCount = hideableColumns.filter(c => !isVisible(c.key)).length

  // Окремої утиліти click-outside у проєкті немає — слухаємо document тут.
  useEffect(() => {
    if (!open) return

    const onMouseDown = (e: MouseEvent) => {
      if (rootRef.current && !rootRef.current.contains(e.target as Node)) setOpen(false)
    }
    const onKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') setOpen(false)
    }

    document.addEventListener('mousedown', onMouseDown)
    document.addEventListener('keydown', onKeyDown)
    return () => {
      document.removeEventListener('mousedown', onMouseDown)
      document.removeEventListener('keydown', onKeyDown)
    }
  }, [open])

  return (
    <div ref={rootRef} className="position-relative d-inline-block">
      <button
        type="button"
        className="btn btn-sm btn-outline-secondary"
        title={hasHidden ? 'Колонки таблиці (частина прихована)' : 'Колонки таблиці'}
        onClick={() => setOpen(v => !v)}
      >
        <i className="bi bi-layout-three-columns" />
        {hiddenCount > 0 && (
          <span className="badge bg-secondary ms-1 py-0" style={{ fontSize: '.65em' }}>
            {hiddenCount}
          </span>
        )}
      </button>

      {open && (
        <div
          className="dropdown-menu show p-2"
          style={{
            top: '100%',
            left: 'auto',
            right: 0,
            minWidth: '210px',
            maxHeight: '320px',
            overflowY: 'auto',
            zIndex: 1050,
          }}
        >
          {hideableColumns.map(col => (
            <div key={col.key} className="form-check mb-1">
              <input
                id={`colsel-${uid}-${col.key}`}
                className="form-check-input"
                type="checkbox"
                checked={isVisible(col.key)}
                onChange={() => onToggle(col.key)}
              />
              <label className="form-check-label small" htmlFor={`colsel-${uid}-${col.key}`}>
                {col.label}
              </label>
            </div>
          ))}

          {hideableColumns.length === 0 && (
            <div className="text-muted small px-1">Немає колонок, які можна приховати</div>
          )}

          {hideableColumns.length > 0 && (
            <>
              <hr className="my-2" />
              <button
                type="button"
                className="btn btn-sm btn-link p-0 small text-decoration-none"
                disabled={!hasHidden}
                onClick={onReset}
              >
                Скинути
              </button>
            </>
          )}
        </div>
      )}
    </div>
  )
}
